### ISSUE TITLE
If running inside Rstudio use debugSource

### ISSUE THREAD

**Issue by hadley** [hadley/testthat#116]
So that breakpoints are respected.

**Comment by hadley** [comment]
@jmcphers it looks like `debugSource()` still doesn't have an argument to control which environment is used. Is that correct?

**Comment by jmcphers** [comment]
@kevinushey added the `local` parameter, which should behave like the `local` parameter to `source`--does that do what you need?

**Comment by hadley** [comment]
Not really - I need to be able to specify an environment, not use the current or global.

**Comment by jmcphers** [comment]
You can set `local` to any environment as well as to TRUE/FALSE.

**Comment by hadley** [comment]
Perfect, thanks!

**Comment by hadley** [comment]
Oh hmmmm, this doesn't work because most of the time tests are called in a separate R session that's not run within RStudio.

**Comment by katrinleinweber** [comment]
Hello! Is this the reason why RStudio's Environment panel doesn't update its content when `auto_test()` runs fail? I noticed this while coding against [exercism problems' tests](http://exercism.io/languages/r/exercises).

Would the ability to display the environment up to the point of a failing test be a feature request for `testthat` or for RStudio?

**Comment by hadley** [comment]
@katrinleinweber can you please file a separate issue? I typically lose track of discussions in closed issues.

**Comment by katrinleinweber** [comment]
@hadley I [posted on SO for now](https://stackoverflow.com/questions/46329973/how-to-update-rstudio-environment-panel-during-testthatauto-test-runs). Will file an issue here if the discussion there doesn't yield an answer.
