### ISSUE TITLE
Port json-deep-compare for comparing lists

### ISSUE THREAD

**Issue by hadley** [hadley/testthat#139]
https://github.com/fhwang/json-deep-compare

**Comment by madrury** [comment]
I believe this feature is something I'm currently interested in, and may take a shot at implementing it.

I'd currently in a situation where I would like the ability to check a nested list object recursively for equality of names and values, ignoring other attributes (which I'm finding various libraries (jsonlite) add as cruft for internal use).  Essentially, the behavior I would like is the `==` operator on python dictionaries.

Among the current suite of options, `test_equal` is too strong

```
> L1 <- list(a = 1, b = 2)
> L2 <- list(a = structure(c(1), foo="bar"), b = 2)
> expect_equal(L1, L2)
Error: L1 not equal to L2
Component “a”: Attributes: < Modes: list, NULL >
Component “a”: Attributes: < Lengths: 1, 0 >
Component “a”: Attributes: < names for target but not for current >
Component “a”: Attributes: < current is not list-like >
```

while `expect_eqivalent` is too weak (it ignores names)

```
> expect_equivalent(L1, L2)  # Pass
> L2 <- list(a = 1, c = 2)
> expect_equivalent(L1, L2)  # Also pass
```

@hadley Was this what you had in mind for this story?  Were you thinking of adding another function in the `expect_[\w]+` family?  Would this be possible for someones first story on the project?

**Comment by hadley** [comment]
@madrury I now think that this belong in a separate package - it now doesn't seem like it belongs in testthat that to me.
