### ISSUE TITLE
Fail to start testing in RStudio

### ISSUE THREAD

**Issue by renkun-ken** [hadley/testthat#187]
I'm using testthat (0.9.0.9000) and in this version the test suddenly cannot be run by `Build -> Test package` with the following error:

```
==> Sourcing R files in 'tests' directory

Error: '\.' is an unrecognized escape in character string starting "'\."
Execution halted

Exited with status 1.
```

Nothing has changed in the package and the previous versions of testthat runs without this problem. 

However, using `Build -> Check package` works fine and the tests run successfully.

My session info:
```rconsole
> sessionInfo()
R version 3.1.1 (2014-07-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] tools_3.1.1
> devtools::session_info()
Session info---------------------------------------------------------------------
 setting  value                       
 version  R version 3.1.1 (2014-07-10)
 system   x86_64, mingw32             
 ui       RStudio (0.98.1062)         
 language (EN)                        
 collate  English_United States.1252  
 tz       Asia/Taipei                 

Packages-------------------------------------------------------------------------
 package    * version date       source        
 devtools     1.6     2014-09-23 CRAN (R 3.1.1)
 rstudioapi   0.1     2014-03-27 CRAN (R 3.1.0)
```

**Comment by hadley** [comment]
Until we get an reproducible example, unfortunately there's nothing we can do  :(

**Comment by geotheory** [comment]
I'm encountering a similar issue with Check. I fail with the following error:
`Error in symbols(d_ag1[, 1:2], squares = sqrt(d_ag1), inches = 0.3, add = T) : 
  T used instead of TRUE
Execution halted [etc...]`
I did have some 'T' instances, but have changed all to 'TRUE' and the problem persists (even after a successful Build & Reload), so it looks like Check is somehow using an previous version.
