### ISSUE TITLE
expect_warning failure

### ISSUE THREAD

**Issue by hughjonesd** [hadley/testthat#203]
```r
checker <- function(expr, errmsg, error=stop) {
  expr_sub <- eval(substitute(substitute(expr)), parent.frame())
  err_sub <- eval(substitute(substitute(errmsg)), parent.frame())
  function(x, vals) {
    res <- tryCatch(eval(expr_sub, list(x=x, vals=vals)), error=error)
    if (isTRUE(res)) return(TRUE) else 
      return(eval(err_sub, list(x=x, vals=vals)))
  }
}

chf <- checker(nonexistent, "myerror", error=warning)
expect_warning(chf(1, list()))
## Error: check_fail(1, list()) no warnings given
## In addition: Warning message:
## In eval(expr, envir, enclos) : object 'nonexistent' not found
```

This is a bit complex. I'm testing my testing library with testthat. In addition, testthat seems to have a bug. So, I'm testing if my function fails to fail appropriately (by giving a warning). But it does not fail to fail. Rather, testthat fails by claiming that chf failed to fail.

**Comment by hadley** [comment]
It works in a simple case:

```R
f <- function(x) {
  warning("!!!")
  x
}
expect_warning(f(1))
```

So that suggests it's something to do with your use of NSE or `tryCatch()`. If you can create a simpler example, I can look into it, but it's not going to be high-priority because the bug is unlikely affect many people and it's going to be horrible to track down because it involves either NSE or the condition system.

**Comment by hughjonesd** [comment]
Heh. Here's the simpler example (NB my original code was even more complex... at the time I thought I'd simplified it a lot, but I was maybe a little stressed.) No NSE is involved, `tryCatch` is the issue.
```
library(testthat)
warnme <-  function() tryCatch(stop("warning"), error=warning)
warnme() # gives a warning
expect_warning(warnme())  
## Error: warnme() no warnings given
## In addition: Warning message:
## In doTryCatch(return(expr), name, parentenv, handler) : warning
```

**Comment by hadley** [comment]
Hmmm, if `tryCatch()` is involved it's probably going to be a nightmare to fix :'(

**Comment by hughjonesd** [comment]
You have my sympathy. Digging a little deeper to within `evaluate_promise`, the issue is related to this:

```r
# does not work:
withCallingHandlers(tryCatch(stop("ooh"), error=warning), warning=function(w){cat("got here")})

# works:
withCallingHandlers(tryCatch(warning("ooh"), warning=warning), warning=function(w){cat("got here")})
```

I think the next chunk shows the root cause:
```r
withCallingHandlers( 
    tryCatch(stop("warning"), error=warning), 
    warning = function(w) cat("got to calling handler"), 
    error = function(e) cat("Outer function stole my error!!!")
)
## Outer function stole my error!!!
## Warning in doTryCatch(return(expr), name, parentenv, handler) : warning
```
In other words, `withCallingHandlers` is catching the error before `tryCatch` does. (Presumably because of lazy evaluation: the `wCH` code runs first.) In `evaluate_promise`, the `warning` handler which adds to the vector of warning messages is therefore never reached.

**Comment by pitakakariki** [comment]
A much simpler example, although I suspect it might not be the same bug.

    f <- function() rbind2(warning("Boo!"))
    f()
    #      [,1]  
    # [1,] "Boo!"
    # Warning message:
    # Boo! 

    expect_warning(f())
    # Error: f() no warnings given
    # In addition: Warning message:
    # Boo! 

Looks like it's something to do with this [weird S4 bug](http://stackoverflow.com/questions/20268021/how-to-catch-warnings-sent-during-s4-method-selection).

**Comment by hadley** [comment]
Ok, I now understand what's going wrong here:

```R
# Doesn't work
withCallingHandlers( 
  tryCatch(
    stop("warning"), 
    error = function(e) {message("e1"); warning(e)}
  ), 
  warning = function(w) message("w"), 
  error = function(e) message("e2")
)

# Works
withCallingHandlers( 
  tryCatch(
    stop("warning"), 
    error = function(e) {message("e1"); warning(e$message)}
  ), 
  warning = function(w) message("w"), 
  error = function(e) message("e2")
)
```

i.e. `warning()` just forwards on the original signal - it doesn't change it from an error. This means the condition handling system sees it as an error, not a warning.
