### ISSUE TITLE
failed <<- TRUE should be done by the Reporter base class

### ISSUE THREAD

**Issue by krlmlr** [hadley/testthat#206]
### Reason

The member is declared and initialized in the base class, and hence should be modified (only) there.

### Implementation

All other reporters will need to `callSuper()` in `add_result()`, and probably also in `start_reporter()`.

### Use case

Different test files use different reporters, like this:

```
with_reporter(MultiReporter$new(reporters = list(get_reporter(), DetailedReporter$new())), {
...
})
```

The "main" file (e.g., `tests/testthat.R`) uses the "basic" reporter only to collect global success status:

```
test_check("tikzDevice", reporter = Reporter$new())
```

Currently I need to implement a subclass to work around this.

**Comment by krlmlr** [comment]
NB: I'm not sure if [`start_reporter()`](https://github.com/hadley/testthat/blob/ddde64e3be5d0cd28ce3093f77aca77c4762ea71/R/reporter.r#L27) should contain the assignment `failed <<- FALSE` at all.

**Comment by hadley** [comment]
I'd be happy to review a PR
