### ISSUE TITLE
Deprecate label & info arguments

### ISSUE THREAD

**Issue by hadley** [hadley/testthat#218]
In favour of teaching people how to accomplish the same thing with NSE.

**Comment by krlmlr** [comment]
Could you please show an example?

**Comment by hadley** [comment]
Look at "building your own testing tools" under http://r-pkgs.had.co.nz/tests.html#test-tests

**Comment by sergiizaskaleta** [comment]
But how will `desc` from `test_that(..)` help when using TeamCity reporter? The only option for reasonable test names are labels
