### ISSUE TITLE
Feature request: conditional adjustment of working directory for "stand-alone" testing

### ISSUE THREAD

**Issue by rappster** [hadley/testthat#221]
Might just be me, but I often put together my unit tests "piece by piece" in the sense that I actually execute explicit calls to `expect_*()` or `test_that()` in a "stand-alone" manner to test things out on an atomic level before, for example, using something like `test()`.

Whenever the actual test code relies on things contained in the `~/tests/testthat` directory, e.g. `tests/testthat/rtools-2.15` in your `devtools` package, running tests that way involves temporarily adjusting the working directory in a manual manner. IMO, this step could/should be automated.

I've put together a function that would handle this (see upcoming pull request)

**Comment by rappster** [comment]
Removed some redundant things: 36de21e0fe25d61d16d41df83bba17a65b8c9e8a

**Comment by hadley** [comment]
I agree that behaviour is super annoying, but I think the correct fix is more like #345

**Comment by rappster** [comment]
Awesome, thanks for putting this in!
