### ISSUE TITLE
Show actual exception message when thrown

### ISSUE THREAD

**Issue by hampei** [hadley/testthat#225]
At the moment, when an exception is thrown only as small code trace is shown like

```
Running the tests in ‘tests/testthat.R’ failed.
Last 13 lines of output:
  9: FUN(X[[2L]], ...)
  10: FUN(X[[2L]], ...)
  11: .local(x, ...)
  12: vapply(x, asJSON, character(1), na = na, auto_unbox = auto_unbox, ...)
  13: FUN(X[[4L]], ...)
  14: FUN(X[[4L]], ...)
  15: .local(x, ...)
  16: stop("No method asJSON S3 class: ", class(x))
  17: base::stop(..., call. = FALSE)
  
  Error: Test failures
```

Which tells me very little of what I need to know. Seeing the actual exception message would really help me a lot more, seeing that it tells me the the class in this instance:

```
No method asJSON S3 class: xyVector
```

It is really slowing me down, especially since I can't seem to output anything myself during the tests to tell me more about my problem (which is apparently done on purpose).

**Comment by hadley** [comment]
Already fixed in the dev version

**Comment by hampei** [comment]
Awesome, thanks!

**Comment by hadley** [comment]
Let me know if you have any feedback on the styling - I've tried to organise it around the fact that you only get to see 13 lines of output. (But you can always get the full output by looking at the log file)
