### ISSUE TITLE
i18n test fails

### ISSUE THREAD

**Issue by kos59125** [hadley/testthat#228]
`test_that` (or `expect_that`) seems ignore i18n settings. The code bellow should pass, but fails.

```r
test_that("test ja", {
   Sys.setenv("LANGUAGE" = "ja")
   expect_equal(Sys.getenv("LANGUAGE"), "ja")  # pass
   expect_equal(gettextf("0 x 0 matrix"), "0 x 0 \u884c\u5217\u3067\u3059")  # fail
})
```

In the interactive:

```r
> Sys.setenv("LANGUAGE" = "en")
> Sys.getenv("LANGUAGE")
[1] "en"
> gettextf("0 x 0 matrix")
[1] "0 x 0 matrix"
> Sys.setenv("LANGUAGE" = "ja")
> Sys.getenv("LANGUAGE")
[1] "ja"
> gettextf("0 x 0 matrix")
[1] " 0 x 0 行列です "
```

Note that `"\u884c\u5217\u3067\u3059"` is equivalent to `"行列です"`.
Japanese translation is supposed to be installed to reproduce.

SessionInfo:

```
R version 3.1.2 (2014-10-31)
Platform: x86_64-apple-darwin13.4.0 (64-bit)

locale:
[1] ja_JP.UTF-8/ja_JP.UTF-8/ja_JP.UTF-8/C/ja_JP.UTF-8/ja_JP.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] testthat_0.9.1

loaded via a namespace (and not attached):
[1] tools_3.1.2
```

**Comment by hadley** [comment]
Hmmm, testthat deliberately sets language to EN to ensure messages are the same across systems

**Comment by kos59125** [comment]
I see. It looks a good idea to fix language for tests. But to do it across system is overdoing to ensure messages. I think it is better if testthat could set non-EN language for each test.

**Comment by hadley** [comment]
I think this just needs to be documented better - I think setting the LANGUAGE for tests is the right thing to do (although there probably should be an option to set to something other than english)

**Comment by hadley** [comment]
Oh hmmm, I thought I set `LANGUAGE = "en"` but I don't. I think it's some weirdness with `gettextf()`:

```R
Sys.setenv("LANGUAGE" = "ja")

f <- function() {
  gettextf("0 x 0 matrix")
}

gettextf("0 x 0 matrix")
# [1] " 0 x 0 行列です "
f()
# "0 x 0 matrix"

```
