### ISSUE TITLE
Weird substitution when using substitute() in test script

### ISSUE THREAD

**Issue by HenrikBengtsson** [hadley/testthat#229]
Consider the following `tests/testthat/test-substitute-bug.R` file:
```r
x <- "foo"
expr <- substitute({ x <- 1 })
print(expr)
```

If I run this script as:
```r
> source("tests/testthat/test-substitute-bug.R")
{
    x <- 1
}
```
I get the expected output, but if I use `test()` the `x` symbol is incorrectly substituted by the value of the global variable `x`;
```r
> devtools::test()
Testing rmini
Hello world!
{
    "foo" <- 1
}
```

To reproduce this, do:
```
git clone --branch=testthat_substitute-bug git@github.com:HenrikBengtsson/rmini.git
R --vanilla
> devtools::test()
```

**Comment by hadley** [comment]
This is known (and annoying) behaviour of substitute - it behaves differently in the global environment.

**Comment by HenrikBengtsson** [comment]
Thanks for this; it can be reproduced using plain R as:
```r
> evalq(source("tests/testthat/test-substitute-bug.R", local=TRUE), envir=new.env())
{
    "foo" <- 1
}
```

**Comment by HenrikBengtsson** [comment]
More importantly, it can be avoided by explicitly setting argument `env` to empty, i.e.
```r
x <- "foo"
expr <- substitute({ x <- 1 }, env=list())
print(expr)
```
Then it also works with devtools/testthat:
```r
> devtools::test()
Testing rmini
Hello world!
{
    x <- 1
}
```
