### ISSUE TITLE
testthat::skip should generate some report/flag we can use downstream (e.g. for coverage testing)

### ISSUE THREAD

**Issue by cboettig** [hadley/testthat#230]
Having run `devtools::check()`  on a package with `testthat` based tests, it would be great if there was a convenient way to determine if any of the tests had been skipped.  

Such a feature would be useful, for instance, in allowing a function like `covr::coveralls()` to detect that tests had been skipped and thus not report the the resulting coverage to coveralls.io.

Thanks to @jimhester for bringing this up and see https://github.com/jimhester/covr/issues/58 for more discussion of the coveralls.io use case.

**Comment by jimhester** [comment]
Thinking about this a little more the only thing that is missing is that there is no way to indicate skipped tests in the `data.frame` returned by the test functions.

Given the following test file

```r
context("test")

test_that("normal tests work", {
  expect_true(TRUE)
})

test_that("skip tests work", {
  skip("this one is skipped")
  expect_true(FALSE)
})

test_that("error tests work", {
  expect_true(FALSE)
})
```
Running 
```r
res <- source_dir('.')
# Error: Test failed: 'error tests work'
# Not expected: FALSE isn't true.

print(res)
#      file context              test nb failed error  user system  real
# 1 test2.R    test normal tests work  0      0 FALSE 0.000      0 0.001
# 2 test2.R    test   skip tests work  1      1 FALSE 0.002      0 0.001
# 3 test2.R    test  error tests work  1      1 FALSE 0.001      0 0.001
```

So the second two tests are indistinguishable apart from the name.  If there was a `skipped` column indicating the number of tests which were skipped @cboettig could then save this result object in his `testthat.R` file and use the results to determine what to do.

**Comment by jwg4** [comment]
This change would allow me to run R tests in a script which has an exit code based on whether or not all the scripts passed. To do this I would also like to be able to distinguish between failed and skipped tests.

**Comment by HarlanH** [comment]
yes, the current behavior, where the `failed` column is 1 for a skipped test, is not what I expected.

**Comment by jimhester** [comment]
So I was just looking into this again today and it does look like it is working correctly if you use `testthat::test_file()`

With the above test file

```r
res <- test_file("test.R")

print(res)
#     file context              test nb failed skipped error  user system  real
# 1 test.R    test normal tests work  1      0       0 FALSE 0.002      0 0.002
# 2 test.R    test   skip tests work  1      0       1 FALSE 0.004      0 0.004
# 3 test.R    test  error tests work  1      1       0 FALSE 0.002      0 0.004
```

Not sure when it was fixed, perhaps before I was using the CRAN release rather than devel.
