### ISSUE TITLE
Testing Reference Class objects

### ISSUE THREAD

**Issue by dougmitarotonda** [hadley/testthat#233]
Perhaps this is not an issue and just user-error, but I had expected that comparing Reference Class objects using `equals` would compare the structure and content of the objects, but that does not seem to be the case. Is this a bug, or am I just going about this the wrong way?

```
Person <- setRefClass("Person", fields = list("name" = "character"))
person1 <- Person$new(name = "Foo")
person2 <- Person$new(name = "Bar")
test_that("object", expect_that(person1, equals(person2))) # passes
test_that("name", expect_that(person1$name, equals(person2$name))) # fails
```

**Comment by hadley** [comment]
The problem is that reference classes are implemented on top of environment, and environments are said to be equal only if they're a pointer to the same place.

**Comment by dougmitarotonda** [comment]
Interesting, thanks for explainin. I guess then my best option given the current structure is to compare the fields directly, right? 

Do you foresee a longer term change in testthat that you think could accommodate Reference Classes? I have no idea the best way to do it, but perhaps `equals` will check its `pryr::otype` and if "RC," then it will check fields, etc. against each other?

**Comment by dougmitarotonda** [comment]
Or I guess I could just implement an `equals` method for the object itself and have that return a logical. That is probably actually easier...

**Comment by dougmitarotonda** [comment]
Just as an update to this, I ended up making `equals` methods for the objects itself and that worked great. So, up to you if you want to close this ticket, though it might make sense to add some documentation on this somewhere in the package.
