### ISSUE TITLE
Order of arguments of `expect_equal` matters?

### ISSUE THREAD

**Issue by dougmitarotonda** [hadley/testthat#241]
My instinct, and nothing in the documentation leads me to believe, that the assignment of which is `object` and `expected` should matter. Am I wrong on this presumption? Or is the following a bug?

```
# This errors
expect_equal(dplyr::data_frame(A = 1:3), data.frame(A = 1:3))
#Error: dplyr::data_frame(A = 1:3) not equal to data.frame(A = 1:3)
#Attributes: < Component “class”: Lengths (1, 3) differ (string compare on first 1) >
#Attributes: < Component “class”: 1 string mismatch >

# This does not error
expect_equal(data.frame(A = 1:3), dplyr::data_frame(A = 1:3))
```

**Comment by hadley** [comment]
It might affect which `all.equal()` method get dispatched

**Comment by dougmitarotonda** [comment]
Hmm, from `all.equal`'s documentation, "`all.equal` is a generic function, dispatching methods on the target argument."

So what is your opinion on this then? Is this:
a) expected behavior (though I argue not intuitive), so just work around it
b) something that should be changed in `all.equal` (very unlikely if I were a betting man)
c) something that should be changed in `testthat`

If a) then for cases like this should I just be using `expect_equivalent` to ignore attributes?

**Comment by hadley** [comment]
I'd say a) - just update your expectations that `expect_equal()` is symmetric :wink:

**Comment by dougmitarotonda** [comment]
Fair enough! Thanks for your prompt feedback.

**Comment by blasern** [comment]
I understand that `expect_equal` will inherently be asymmetric because of the method dispatch. But could we have `expect_equal` call `all.equal` with the arguments in the same order?

    # create data
    df <- data.frame(x = 1)
    tbl <- dplyr::data_frame(x = 1)
    
    # compare df with tbl 
    all.equal(df, tbl)
    ## [1] "Attributes: < Component “class”: Lengths (1, 3) differ (string compare on first 1) >"
    ## [2] "Attributes: < Component “class”: 1 string mismatch >"  
    testthat::expect_equal(df, tbl)
    
    # compare tbl with df
    all.equal(tbl, df)
    ## [1] TRUE
    testthat::expect_equal(tbl, df)
    ## Error: tbl not equal to df
    ## Attributes: < Component “class”: Lengths (1, 3) differ (string compare on first 1) >
    ## Attributes: < Component “class”: 1 string mismatch >

It seems that in `testthat::equals` the function `compare` using `compare(expected, actual, ...)` instead of `compare(actual, expected, ...)`. Just changing this line would fix the issue, but might break the messages.
