### ISSUE TITLE
test timeout function (similar to node.js mocha timeout)

### ISSUE THREAD

**Issue by jmarca** [hadley/testthat#242]
Hi I am currently staring at a spinner in Emacs from a test that didn't return from hitting a database.

I am relatively new to using testthat and devtools, so I'm not sure where to file this feature request, but it would be nice if tests could be set up to fail if a some timeout has elapsed.

In this case, RCurl has decided not to return because the function is broken.  It would be nice to have tests abort if they don't run quickly (say 2 seconds) and if I expect to run longer-duration tests, set an option perhaps via some hack like:

```
options(testthat = list(
            timeout = 0 ## 0 means no timeout
            )
)
```

I'm coming from writing tests in node.js using mocha, and this feature is very helpful during development when code breaks more often.

**Comment by hadley** [comment]
I think you could just use `setTimeLimit()` in your tests
