### ISSUE TITLE
Expect_error failing in case of a long error message

### ISSUE THREAD

**Issue by robertness** [hadley/testthat#243]
I used expect_error as follows

    expect_error(f(a, b),  "Objects being traversed (vertices/edges) must have 'updated' and 'name' attributes.")

   >  Error: f(a, b) does not match 'Objects being traversed (vertices/edges) must have 'updated' and 'name' attributes.'. 
    Actual value: "Error in checkAttributes(g, S) : \n  Objects being traversed (vertices/edges) must have 'updated' and 'name' attributes.\n"

It worked after using a shorter (less informative) error

**Comment by hadley** [comment]
Clearly something is line-breaking your error message. Probably easiest to just do a partial match
