### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by kforner** [hadley/testthat#251]
I want to use [Sourcegraph](https://sourcegraph.com) for testthat code search, browsing, and usage examples. Can an admin enable Sourcegraph for this repository? Just go to https://sourcegraph.com/github.com/hadley/testthat. (It should only take 30 seconds.)

Thank you!

**Comment by gaborcsardi** [comment]
@kforner It does not seem to support R or even C/C++. Can you actually use it from R packages?

**Comment by kforner** [comment]
Yes you're right, I can not make it work on my repos.
