### ISSUE TITLE
SummaryReporter always completes with DONE when test file changes during autoreporting

### ISSUE THREAD

**Issue by cocinerox** [hadley/testthat#252]
Even when there is a failure, e.g.:
`test-1.R` changes to: `test_that("This is a failure", fail())`
Terminal shows:
```
Rerunning tests:  test-1.R
1
1. Failure: This is a failure ----------

Failure has been forced

DONE
```

The reason behind this might be `with_reporter("summary",test_file("test-1.R"))` which always puts the "DONE". Other reporters don't do this.

**Comment by cocinerox** [comment]
Embedding the body of the `end_reporter` function of the `SummaryReporter` into `if (has_tests) {...}` seems like to solve the problem - however I'm not sure this condition was omitted deliberately. Can provide a PR if needed.

**Comment by hadley** [comment]
DONE just implies the tests are complete, not that they're correct. I'm not sure what the problem is?

**Comment by cocinerox** [comment]
When using e.g. `reporter="minimal"`, DONE means all tests are OK. It's enough to check for this DONE, and you're good. However, `reporter="summary"`, always puts the DONE. Furthermore, when all tests pass, it puts DONE twice... It is not a serious issue, but slightly inconvenient and not consistent IMO.

**Comment by cocinerox** [comment]
Thanks!
