### ISSUE TITLE
check reporter should include file name/line number

### ISSUE THREAD

**Issue by hadley** [hadley/testthat#253]

**Comment by Ironholds** [comment]
If this should be read as "when a problem occurs, give the file and line number it occurred on" a big +1 from me. I was just having a conversation with one of the CRAN people about it.

**Comment by hadley** [comment]
Hmmm, although it did work in the issue I just filed at https://github.com/Ironholds/webreadr/issues/16

**Comment by Ironholds** [comment]
How were you running the tests?

**Comment by hadley** [comment]
R CMD check via `check()` via `revdep_check()`

**Comment by Ironholds** [comment]
Hrn! CRAN reports an absence of line numbers. I wonder how they're running it.

**Comment by hadley** [comment]
There are unit tests for this and it does seem to work for me, so I'm going to close. Please ping me if you can make a reproducible example.
