### ISSUE TITLE
new behavior of suppressing messages and warnings in tests is wrong

### ISSUE THREAD

**Issue by kforner** [hadley/testthat#254]
Because:

1) warnings can be very useful to detect bugs in the tests and in the code to be tested 
 If you want to get rid of some (once you understand them, just suppress them using suppressMessages or suppressWarnings, or better test them using expect_warning

2) now it is impossible to test code that deals with warnings. For instance suppose that you want to test a function that turns warnings into errors using the warn=2 option, it does no longer work in testthat tests. 

3) code does not behave like in the real R world.

just my opinion.

**Comment by hadley** [comment]
Hmmm, I think that ignoring messages is the right thing to do (in the same way printed output is ignored), but ignoring warnings might be too much.

**Comment by kforner** [comment]
Agreed.

**Comment by kforner** [comment]
great !
