### ISSUE TITLE
expect_silent()

### ISSUE THREAD

**Issue by hadley** [hadley/testthat#261]
i.e. no output, warnings, messages or errors.

**Comment by mmaechler** [comment]
I was looking for   `expect_no_message()`  and  `expect_no_warning()`  which are a bit more fine grained than just "silent".   Also, I'd expect errors to trigger anyway, so there's no need to mention them here (or in the new functionality code).

**Comment by pitakakariki** [comment]
I'd expect everything I test to be silent. I wonder if there's a way of implementing this that doesn't have nearly every test basically duplicated?

    expect_equal(f(), 42)
    expect_silent(f())

**Comment by hadley** [comment]
I think would just test for absence of warnings, messages and output, since errors should be handled otherwise. Messages and output are usually ignored, and warnings will bubble up (once #254) is fixed.

@mmaechler this would be in addition to #219
