### ISSUE TITLE
Scoping Issue within Test

### ISSUE THREAD

**Issue by wsloand** [hadley/testthat#266]
With the same test run manually vs. through test_dir, the result changes.

I have a function, business below, that when I run the test manually, it works without issue.  When I run it automatically with test_dir, it fails.  I think that it's a scoping issue with the formula evaluation, but I can't seem to isolate the problem.

Specifically, here is the function and the pair of tests:

    business <- function(FUN,
                         zero.missing=FALSE,
                         max.missing=0.5)
      function(x, ...) {
        ## Allow functional input instead of numeric/logical
        if (inherits(zero.missing, "formula"))
          zero.missing <- eval(zero.missing[[2]])
        if (inherits(max.missing, "formula"))
          max.missing <- eval(max.missing[[2]])
        mask.missing <- is.na(x) | (zero.missing & (x %in% 0))
        if (sum(mask.missing)/length(x) > max.missing)
          return(NA)
        FUN(x[!mask.missing], ...)
      }

Tests:

    test_that("business", {
      choice <- function() TRUE
      b.mean.3 <- business(mean, zero.missing=~choice())
      expect_equal(b.mean.3(c(0, 1)), 1)
      choice <- function() FALSE
      expect_equal(b.mean.3(c(0, 1)), 0.5)
    })

And the way that I'm loading it is:

    rm(list=ls())
    
    library(devtools)
    library(covr)
    library(testthat)
    library(shiny)
    
    load_all(".")

When I just run the tests on the R command prompt (everything inside the test_that code block above), it works:

    >   b.mean.3 <- business(mean, zero.missing=~choice())
    >   expect_equal(b.mean.3(c(0, 1)), 1)
    >   choice <- function() FALSE
    >   expect_equal(b.mean.3(c(0, 1)), 0.5)
    >

When I run them automatically (along with a lot of other tests), it fails

    > test_dir("tests/")
    [ skipped unrelated output ]
    2. Error: business -------------------------------------------------------------
    could not find function "choice"
    1: withCallingHandlers(eval(code, new_test_environment), error = capture_calls)
    2: eval(code, new_test_environment)
    3: eval(expr, envir, enclos)
    4: expect_equal(b.mean.3(c(0, 1)), 1) at test-pk.business.rules.R:61
    5: expect_that(object, equals(expected, label = expected.label, ...), info = info, label = label)
    6: condition(object)
    7: compare(expected, actual, ...)
    8: compare.default(expected, actual, ...)
    9: all.equal(x, y, ...)
    10: all.equal.numeric(x, y, ...)
    11: attr.all.equal(target, current, tolerance = tolerance, scale = scale, ...)
    12: mode(current)
    13: b.mean.3(c(0, 1))
    14: eval(zero.missing[[2]]) at c:\Users\Bill Denney\Desktop\pknca\trunk/R/pk.business.rules.R:27
    15: eval(expr, envir, enclos)

**Comment by fabian-s** [comment]
Similar issue with tests for https://github.com/refunders/refund/tree/devel: 
For a test 

```
test_that("ff identifiability stuff works", {
    skip_on_cran()

    set.seed(112)
    n <- 20
    ngrid <- 50
    s <- t <- seq(0, 1, l=ngrid)
    Xefcts <- t(poly(t, 2))
    X <- matrix(rnorm(n*2), n, 2) %*% Xefcts
    L <- matrix(1/ngrid, ncol=ngrid, nrow=n)
    LX <- L*X
    beta.st <- outer(s, t, function(s, t) cos(3*pi*t)*s)
    Y <- LX%*%beta.st
    data <- data.frame(Y=I(Y), X=I(X))

    expect_warning(m <- pffr(Y ~ ff(X, xind=s), yind=t, data=data))
    expect_equal(class(m$smooth[[2]]$margin[[1]]), "pss.smooth")

  })
```
we get 

```
Running the tests in ‘tests/testthat.R’ failed.
Last 13 lines of output:
         e$calls <- head(sys.calls()[-seq_len(frame + 7)], -2)
         signalCondition(e)
     }, "no applicable method for 'smooth.construct' applied to an object of class \"pss.smooth.spec\"", 
         quote(UseMethod("smooth.construct")))
```

even though that method is defined by the package, whereas 
`devtools::test()`, `devtools::check()` and `testthat::test_file()` all run fine.

**Comment by hadley** [comment]
Where is that method defined?

**Comment by mwmclean** [comment]
Yeah, the issue reported by @fabian-s came up because the S3 method was not declared in the NAMESPACE.  Fixing that fixed the problem.  I am still curious why `devtools::load_all` followed by `testthat::test_file` does not have a problem with the missing declarations.

**Comment by pdbailey** [comment]
I'm having an issue that I think is related

I define a function named "inlf" for the lfactors package and then make it a generic for %in% with this code in .onLoad in a file called "zzz.R"

	setGeneric("%in%", where=.GlobalEnv)
	setMethod("%in%", signature(x="lfactor"), inlf, where=.GlobalEnv)
	setMethod("%in%", signature(table="lfactor"), inlf, where=.GlobalEnv)
	setMethod("%in%", signature(x="lfactor", table="lfactor"), inlf, where=.GlobalEnv) 

I cannot then use %in% when calling the tests via test_check("lfactors"). Basically, it does not work then via R CMD CHECK or test_chedk("lfactors") when run interactively. But if I copy and paste in the test code it runs without error.

I tried copying the setGeneric and setMethod code over to the top of the test but that didn't work either.

Am I missing something obvious here?

Looking at mwmclean's reply I wonder if I'm supposed to include %in% in the NAMESPACE, but I don't think I'm supposed to, just inlf (which is in there).

**Comment by hadley** [comment]
It's almost certainly not an issue in testthat, which I'm 99% sure is correct. Unfortunately I don't have the time to help debug individual issues - not to mention it's frustrating enough to deal with my own code that has problems, let alone someone else!

**Comment by billdenney** [comment]
I've finally been able to generate a reprex for this one.  First a failure, then by simply removing the test_that wrapper, success.

``` r
library(testthat)
foo <- function(obj) UseMethod("foo")

foo2 <- function(obj) {
  foo(obj)
}

test_that("foo2 fails", {
  foo.character <- function(obj) {
    paste(obj, obj)
  }
  expect_equal(foo2("hi"), "hi hi")
})
#> Error: Test failed: 'foo2 fails'
#> * no applicable method for 'foo' applied to an object of class "character"
#> 1: expect_equal(foo2("hi"), "hi hi") at <text>:12
#> 2: compare(object, expected, ...)
#> 3: foo2("hi")
#> 4: foo(obj) at <text>:5
```
``` r
library(testthat)
foo <- function(obj) UseMethod("foo")

foo2 <- function(obj) {
  foo(obj)
}

# foo2 has the expected result
foo.character <- function(obj) {
  paste(obj, obj)
}
foo2("hi")
#> [1] "hi hi"
```

**Comment by etiennebr** [comment]
@billdenney, have you found a fix for this issue? I tried multiple unsuccessful strategies to move the function to the search path.

**Comment by hadley** [comment]
@billdenney can you please file an new issue with a specific title

**Comment by CSJCampbell** [comment]
@wsloand's issue is due to the formula class capturing the environment from which it is called, but `[.formula` discarding this. A bit late to the party, but I had a similar issue and Google brought me here, so here is a demo and a code solution.

    # minimal original example
    f1 <- function(expr) {
        function() {
            # discards environment
            eval(expr[[2]])
        }
    }
    # reuse example
    f2 <- function(expr) {
        function() {
            # formula contains environment
            eval(expr[[2]], env = environment(expr))
        }
    }
    # this runs correctly for `h2` but throws error at `h1`
    test_that("test_that expression functions in scope", {
        g <- function() TRUE
        # no error
        h2 <- f2(~g())
        expect_true(h2())
        # original error
        h1 <- f1(~g())
        expect_true(h1())
    })
