### ISSUE TITLE
Suggest expect_equal_df for data.frames

### ISSUE THREAD

**Issue by wsloand** [hadley/testthat#273]
I find myself often spending a good bit of time with data.frame checks on expect_equal just keeping the columns in order.  I'm currently writing a package where as it continues to develop, the column order for function outputs will continue to evolve.

It would be nice to have a function like the below available so that I could develop tests based on data.frame content with optional requirements of column and row ordering.

    expect_equal_df <- function (object, expected, ..., info = NULL, label = NULL,
                                 expected.label = NULL,
                                 require.column.order=FALSE,
                                 require.row.order=TRUE) {
      if (is.null(label)) {
        label <- find_expr("object")
      }
      if (is.null(expected.label)) {
        expected.label <- find_expr("expected")
      }
      if (!is.data.frame(object))
        stop("object must be a data.frame")
      if (!is.data.frame(expected))
        stop("expected must be a data.frame")
      if (!require.column.order) {
        object <- object[, sort(names(object)), drop=FALSE]
        expected <- expected[, sort(names(expected)), drop=FALSE]
      }
      if (!require.row.order) {
        object <- object[do.call(order, object),,drop=FALSE]
        expected <- expected[do.call(order, expected),,drop=FALSE]
      }
      expect_that(object, equals(expected, label = expected.label, 
                                 ...), info = info, label = label)
    }

**Comment by hadley** [comment]
One approach is to use `tbl_df`s and the `all.equal()` method that dplyr defines for them.
