### ISSUE TITLE
rep$start_context(desc) : could not find function ".oapply"

### ISSUE THREAD

**Issue by ldecicco-USGS** [hadley/testthat#277]
On R Under development (unstable) (2015-07-05 r68627) -- "Unsuffered Consequences", my package is failing with the following message:

```
> library(testthat)
> library(dataRetrieval)
> test_check("dataRetrieval")
Error in rep$start_context(desc) : could not find function ".oapply"
Calls: test_check ... sys.source2 -> eval -> eval -> context -> <Anonymous>
In addition: Warning messages:
1: In initialize(value, ...) :
  Class definition for Class "CheckReporter" doesn't have a parent environment for objects defined.  Bug??
2: In initialize(value, ...) :
  Class definition for Class "ListReporter" doesn't have a parent environment for objects defined.  Bug??
3: In initialize(value, ...) :
  Class definition for Class "MultiReporter" doesn't have a parent environment for objects defined.  Bug??
Execution halted
```
This version didn't cause the problem:
 version  R Under development (unstable) (2015-06-28 r68602)

But this version does:
version  R Under development (unstable) (2015-07-04 r68627)

I'm still digging around to make sure it's not a problem with my package, but the error message makes me think it's `testthat`.

**Comment by hadley** [comment]
It's a problem with r. Should be fixed shortly
