### ISSUE TITLE
Some machinery to test in another R session

### ISSUE THREAD

**Issue by gaborcsardi** [hadley/testthat#282]
Maybe this is stupid, but some things are just impossible to test otherwise. E.g. I want to define a new error handler (i.e. `options(error = func)`) in a test case, and don't see another way of doing it.

**Comment by krlmlr** [comment]
`devtools` has facilities to run stuff in a new R session, such as `devtools::RCMD` and `devtools:::R`. I find it difficult to use this from tests, though.

**Comment by gaborcsardi** [comment]
Thanks. For my problem I think I found another solution, so I think I'll just close this issue, it is quite specific.
