### ISSUE TITLE
feature request: expect_in()

### ISSUE THREAD

**Issue by BayesyBrad** [hadley/testthat#298]
Sometimes you want to check that a variable takes the value of some acceptable set.  For myself this is usually from some some kind of user input or scraped text.  It can be quicker and easier to just specify a vector of acceptable values, and then test that the variable in question's value is in that vector than to specify a rule set.  

example:
expect_in(car_color, c("red", "blue", "green"))

Anyone agree?

**Comment by kevinushey** [comment]
IMHO I would prefer to just see `expect_true(x %in% c(...))`.

**Comment by BayesyBrad** [comment]
I think you're right, that's simpler.  closing.
