### ISSUE TITLE
Negation of tests

### ISSUE THREAD

**Issue by krlmlr** [hadley/testthat#303]
For "old-style expectations", there is `not()` -- e.g., `expect_that(object, not(is_null(...)))`: http://stackoverflow.com/a/30037495/946850. I'm not aware of a way to achieve this with the "new style". How about the following syntax:

```
n(expect_null)(object)
```

The package could also define

```
nexpect_null <- n(expect_null)
```

(same for all other functions).

At the core is the function `nexpect_that()` which is `expect_that()` with a negated condition. The function `n()` would be implemented by substituting `expect_that` with `nexpect_that` in the body.

**Comment by hadley** [comment]
I don't like negative in general - I'd rather you assert what you want, rather than what you don't want.

**Comment by krlmlr** [comment]
Thanks, that's very helpful advice not only for testing ;-) I still think that "negated" versions could be useful for a few of the existing expectations:

- expect_error() -> expect_success()
    - I vaguely remember a discussion about this, but couldn't find it
- expect_less_than() -> expect_less_than_or_equal()
- expect_greater_than() -> expect_greater_or_equal()
- expect_named() -> expect_unnamed()

Should be fairly easy, no need to compute on the language.

**Comment by hadley** [comment]
Yeah I think those are reasonable additions. If you want to add them, please use expect_silent as template for a "modern" expectation.

**Comment by krlmlr** [comment]
I'll add them.
