### ISSUE TITLE
Strange output if used with colorout package

### ISSUE THREAD

**Issue by while** [hadley/testthat#312]
As testthat prints its output in color it interferes with other coloring packages, such as colorout (https://github.com/jalvesaq/colorout). 

**Example**
```r
# without colorout
R> devtools::test()
Loading kml
Testing kml
...

# with colorout
R> library(colorout)
R> devtools::test()
Loading kml
Testing kml
1;32m.0m1;32m.0m1;32m.0m

**Comment by gaborcsardi** [comment]
So, how about turning off testthat colors then? :)

**Comment by while** [comment]
How do you do that? I can't find any info on it.

**Comment by gaborcsardi** [comment]
`options(testthat.use_colours = FALSE)` should do it I think.

**Comment by while** [comment]
Thansk!
