### ISSUE TITLE
FR: Message about failed expect_identical() should include dput() result

### ISSUE THREAD

**Issue by krlmlr** [hadley/testthat#321]
...of both expected and actual, at least the first few lines.

**Comment by hadley** [comment]
I wonder if we should pull `compare` out into its own package...

**Comment by krlmlr** [comment]
Good idea, but also potentially a lot of work. However, this issue is unrelated: it's about the code path where compare() isn't called (because objects are equal) but the message "Objects equal but not identical" is uninformative.

**Comment by hadley** [comment]
Ok got it. I'll think about this today, but I suspect dput won't work well for many types of output. I think the right thing to do would be to write our own version of all.equals, but that is a lot of work to do correctly.

**Comment by hadley** [comment]
Do you have an example where this would help?

**Comment by krlmlr** [comment]
In any case where expect_identical() is used but fails because the objects are equal but not identical. There can be a multitude of reasons for this, a dput() output might help diagnosing them.

It's not terribly important, one can always set a breakpoint and inspect, or perhaps ask testthat to stop on the first broken test (#356).
