### ISSUE TITLE
testthat fails, yet same code works in a standard test

### ISSUE THREAD

**Issue by hofnerb** [hadley/testthat#322]
In my package [papeR](https://github.com/hofnerb/papeR) I have the following lines in my code
```r
## overwrite standard generic
labels <- function(object, ...)
    UseMethod("labels")

## per default fall back to standard generic
labels.default <- function(object, ...)
    UseMethod("base::labels")
```

If I am using
```
labels(matrix(1:10))
``` 
in a standard file in `tests`, e.g. in `tests/regtest-prettify.R` everything works as expected and I get
```
## [[1]]
## [1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10"
## 
## [[2]]
## [1] "1"
```
The same is true if I run the code after installing the package.

Yet, if I put this code in `tests/testthat/test-labels.R`, I get (essentially) the following error
```
no applicable method for 'base::labels' applied to an object of class "c('matrix', 'integer', 'numeric')"
```

Now, I wonder 
a) why this happens 
b) why this happens only with testthat
c) how  I can debug and solve this.

**Comment by kevinushey** [comment]
This fails directly for me (ie, is not a `testthat` issue):

```
## overwrite standard generic
labels <- function(object, ...)
    UseMethod("labels")

## per default fall back to standard generic
labels.default <- function(object, ...)
    UseMethod("base::labels")

labels(matrix(1:10))
```

Either way, do you _really_ want to override the generic? Can't you just implement a `labels` method for your own class?

**Comment by hofnerb** [comment]
That's true. But
```r
install_github("hofnerb/papeR")
library("papeR")
labels
labels(matrix(1:10))
``` 
does work, though.

In essence I currently do not need to overwrite the standard generic. However, I wanted to add a special behaviour such that I can extract variable labels by 
```r
df <- data.frame(x = 1:3, y  = 4:6)
df <- as.ldf(df)
labels(df$x)
```
which should return
```r
attr(df$x, "variable.label")
```

I was thinking of something along the lines of
```r
labels.default <- function(object, ...) {
    if (!is.null(attr(object, "variable.label"))) {
        return(attr(object, "variable.label"))
    }
    UseMethod("base::labels")
}
```
which wouldn't change standard behaviour per se. [We had this discussion already elsewhere btw].

----
However, I was just thinking to also give a new (additional) class to all "columns" of the data frame to allow method dispatch to work. 

Still, I am puzzled why this happens that way.

**Comment by hadley** [comment]
I think you want `base::labels(object, ...)`, not `UseMethod("base::labels")`.  But I agree with @kevinushey that override a generic is a bad idea.
