### ISSUE TITLE
expect_equal for data.table

### ISSUE THREAD

**Issue by terrytangyuan** [hadley/testthat#324]
Looks like when expect_equal two data.tables, it also compares unneccessarily the attributes such as 
```
$.internal.selfref
<pointer: 0x10200eb78>
```
This will give the following error
 ```
Error: result not equal to expected
Attributes: < Length mismatch: comparison on first 1 components >
```

The quick fix is to convert the data.tables to data.frames. 

@hadley I am working on a PR for this but any preferred way to fix this?

**Comment by hadley** [comment]
I think data.table should probably provide a `all.equal.data.table` method
