### ISSUE TITLE
Move NEWS.md to inst/NEWS.md and make it permanent

### ISSUE THREAD

**Issue by hofnerb** [hadley/testthat#325]
Currently, there exists no news file (in any format) in the CRAN source package. I think that a NEWS file should be an essential ingredient of the package, though. Even more as it exists (but only on github).

One could always set a link from NEWS or NEWS.md to inst/NEWS.md.

**Comment by hadley** [comment]
I'm not interested in fighting with CRAN about this. I think a news file belongs in the root dir of source and installed.

**Comment by hofnerb** [comment]
That might be true, yet, you currently have NO news at all instead of 
news in the correct location. I think that is even worse.

Am 27.11.2015 um 21:07 schrieb Hadley Wickham:
> I'm not interested in fighting with CRAN about this. I think a news file
> belongs in the root dir of source and installed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hadley/testthat/issues/325#issuecomment-160198829>.
>

-- 
******************************************************************************
Dr. rer. nat. Benjamin Hofner

Institut für Medizininformatik, Biometrie und Epidemiologie
Friedrich-Alexander-Universität Erlangen-Nürnberg
Waldstr. 6 - 91054 Erlangen - Germany

Tel: +49-9131-85-22707
Fax: +49-9131-85-25740

Büro:
   Raum 3.036
   Universitätsstraße 22
   (Eingang linke Seite des Gebäudes; Wegweiser IMBE)

benjamin.hofner@fau.de

http://www.imbe.med.uni-erlangen.de/cms/benjamin_hofner.html
http://www.benjaminhofner.de
******************************************************************************

**Comment by robertzk** [comment]
Would a symlink be a compromise?
