### ISSUE TITLE
`doesnt` as alternative to `not` to avoid magrittr name conflict

### ISSUE THREAD

**Issue by jackwasey** [hadley/testthat#331]
I find that I have to write testthat::not pretty often, as I may have loaded testthat before magrittr. Can I suggest adding an alias to `not` called `doesnt`. It's not perfect, having the punctuation omitted, and the grammar of `doesnt(throws_error(...` makes me wince, but this could also be aliased to `throw_error`. `does_not` might be better.

This is not just cosmetic, as I have spent time debugging tests where I used plain `not` and `magrittr::not` confused `testthat`.

**Comment by hadley** [comment]
I'm soft deprecating not - with the new `NA` support in `expect_message()`, you shouldn't need to use it any more.
