### ISSUE TITLE
taskCallbacks not respected in test

### ISSUE THREAD

**Issue by drknexus** [hadley/testthat#333]
I have [a package](https://github.com/drknexus/mcparallelDo) in which the test conditions appear to be met when the code runs interactively, but not when run through the testthat framework. As far as I can tell, what is happening is that while in testthat the taskCallback handler I'm establishing isn't being triggered.  Is that expected/desirable behavior?

**Comment by hadley** [comment]
Task callbacks are only called at the completion of a "top-level task", which in this context is probably the test (or higher, maybe even the complete test suite). I don't know how you could work around this, as it's a fundamental limitation of task callbacks.
