### ISSUE TITLE
Autorun Examples as Tests

### ISSUE THREAD

**Issue by billdenney** [hadley/testthat#335]
Would it be possible to add a feature to run documentation examples as tests?  I'd love to write the examples once in a way that best-helps the user understand the code, but the simple "does it give an error" check that happens during `R CMD check` doesn't give assurance that the test worked.

It separates the tests into two locations (bad) but it is a write-once solution (good).  Feel free to tell me that this doesn't align with the plans for testthat.

I initially asked this question on stackoverflow for roxygen2, but thinking more, it seems like a devtools feature (http://stackoverflow.com/questions/34080889/can-i-automatically-generate-unit-tests-for-testthat-from-roxygen2-examples).

**Comment by hadley** [comment]
This doesn't align with my vision for testthat, sorry.
