### ISSUE TITLE
Totally Stoked re: catch

### ISSUE THREAD

**Issue by Thell** [hadley/testthat#336]
:clap:  Fantastic! I can't wait to see how this pans outs.

I would be spectacular to be able to have the block

~~~
#ifdef CATCH_CONFIG_RUNNER

inline bool run_tests()
{
  static Catch::Session session;
  return session.run() == 0;
}

#endif
~~~

setup such that it _could_ be customized in `test-runner.cpp`. (ie: print durations, return test/context info to custom reporters and such).

What's next? Integrate something like the header only c++ [benchpress](https://github.com/bigdatadev/benchpress) lib?

**Comment by Thell** [comment]
@kevinushey I've wanted to be able to run my cpp tests in a more automated fashion for a while now, and thanks to your patch it looks promising...

The limitation of not being able to pass in options really bugs me, so to test what could be done about it I copied the `testthat/inst/include/tests/testthat.h` file into a project as `src/test-runner.h`, changed the include to `tests/vendor/catch.h`, then created the following `src/test-runner.cpp`...

~~~c++
#define TESTTHAT_TEST_RUNNER
#include "test-runner.h"

#include <Rcpp.h>

//' @export
// [[Rcpp::export]]
bool run_catch_test_reporter(Rcpp::CharacterVector args = "")
{
  static Catch::Session session;
  static const auto orig_configData = session.configData();

  std::vector<std::string> tmp = Rcpp::as<std::vector<std::string>>(args);
  tmp.insert(tmp.begin(), "catch");
  std::vector<char*> argv;
  for ( auto& e : tmp ) {
    if (!e.empty()) {
      argv.push_back( &e[0] );
    }
  }
  int argc = argv.size();

  session.useConfigData(orig_configData);
  if (argc > 1) {
    session.applyCommandLine(argc, &argv[0]);
  }
  return session.run() == EXIT_SUCCESS;
}
~~~

Now, from the console I can get quite a bit more control. Basic usage looks good, but I haven't tried anything else yet.

~~~
		> run_catch_test_reporter()
		===============================================================================
		All tests passed (3 assertions in 2 test cases)
		
		[1] TRUE
~~~
or
~~~
		> run_catch_test_reporter("-d yes")
		two plus two equals four completed in 8e-06s
		rcpp_hello tests | rcpp_hello.cpp completed in 0.000137s
		floating point tests work completed in 1e-05s
		rcpp_hello tests | rcpp_hello.cpp completed in 0.000113s
		A completed in 7e-06s
		===============================================================================
		All tests passed (3 assertions in 2 test cases)
		
		[1] TRUE
~~~
or
~~~
		> run_catch_test_reporter("-s")
		
		~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
		catch is a Catch v1.2.1 host application.
		Run with -? for options
		
		-------------------------------------------------------------------------------
		rcpp_hello tests | rcpp_hello.cpp
		  two plus two equals four
		-------------------------------------------------------------------------------
		rcpp_hello.cpp:22
		...............................................................................
		
		rcpp_hello.cpp:24: 
		PASSED:
		  CATCH_CHECK( twoPlusTwo() == 4 )
		with expansion:
		  4 == 4
		
		-------------------------------------------------------------------------------
		rcpp_hello tests | rcpp_hello.cpp
		  floating point tests work
		-------------------------------------------------------------------------------
		rcpp_hello.cpp:22
		...............................................................................
		
		rcpp_hello.cpp:27: 
		PASSED:
		  CATCH_CHECK( 22/7 == Approx( 3.141 ).epsilon( 0.2 ) )
		with expansion:
		  3 == Approx( 3.141 )
		
		-------------------------------------------------------------------------------
		A
		-------------------------------------------------------------------------------
		rcpp_hello.cpp:31
		...............................................................................
		
		rcpp_hello.cpp:32: 
		PASSED:
		  CATCH_CHECK( 1 + 1 == 2 )
		with expansion:
		  2 == 2
		
		===============================================================================
		All tests passed (3 assertions in 2 test cases)
		
		[1] TRUE
~~~

and the options reset...

~~~
		> run_catch_test_reporter()
		===============================================================================
		All tests passed (3 assertions in 2 test cases)
		
		[1] TRUE

~~~

**Comment by kevinushey** [comment]
Looks nice! I wonder if the default argument could be controlled with an option, e.g. `getOption("testthat.catch.options")`? That way, `testthat` could automatically run `catch` respecting whatever flags you'd like to pass to the executable.

**Comment by Thell** [comment]
Being able to set/pass options would be great.  iirc, @hadley mentioned in an earlier issue something about not wanting to have functions using `getOption` unless really needed. Just being able to set some options via `expect_cpp_tests_pass` and the various `test_XXX` commands would be nice.

This evening I was planning to take a look at what could be done about the darned `Session` singleton. Perhaps tearing it down on each call, or providing a `get_instance()`. If the `testthat` runner wants to have a static session, then to play nice it'll need to be exposed _somewhere_ or provide a method to set the options. Perhaps instead of a `getOption` a specific `CatchReporter` class? That's above my understanding of `testthat` structure though. :)

**Comment by kevinushey** [comment]
My preferred way of providing singletons is just with a function return a reference to a static local, e.g.

```cpp
Catch::Session catchSession() {
    static Catch::Session instance;
    return instance;
}
```

which seems like it could be sufficient here?

**Comment by Thell** [comment]
Having the instance available is definitely all that's needed from my point of view. The beauty of both `testthat` _and_ `catch` is they are meant to be simple _and_ useful without much fuss.

Being that the `Catch::Session` is non-copyable I went with 

~~~c++
#ifdef CATCH_CONFIG_RUNNER

std::reference_wrapper<Catch::Session> catchSession() {
  static Catch::Session session;
  std::reference_wrapper<Catch::Session> instance(session);
  return instance;
}

inline bool run_tests()
{
  Catch::Session& session = catchSession();
  return session.run() == EXIT_SUCCESS;
}
#endif
~~~

in the `test-runner.h` (in my package's local `src`) and the `test-runner.cpp` is slightly modified to restore the pssed session's config. No more worries about the singleton, and full control over the config "within" my space without mucking up the `testthat` funcs. That control, as you surmised, constitutes 'useful' for me. Perhaps, simply making something like the above `catchSession()`, and a documentation or wiki entry regarding `custom catch runners` is enough?


~~~c++
#define TESTTHAT_TEST_RUNNER
#include "test-runner.h"

#include <Rcpp.h>

//' @export
// [[Rcpp::export]]
bool run_catch_test_reporter(Rcpp::CharacterVector args = "")
{
  std::vector<std::string> tmp = Rcpp::as<std::vector<std::string>>(args);
  tmp.insert(tmp.begin(), "catch");
  std::vector<char*> argv;
  for ( auto& e : tmp ) {
    if (!e.empty()) {
      argv.push_back( &e[0] );
    }
  }
  int argc = argv.size();

  int return_code = 1;
  Catch::Session& session = testthat::catchSession();
  const auto orig_configData = session.configData();
  if (argc > 1) {
    return_code = session.applyCommandLine(argc, &argv[0]);
  } else {
    return_code = 0;
  }
  
  if (return_code == 0) {
    return_code = session.run();
  }
  // restore the testthat config.
  session.useConfigData(orig_configData);

  return return_code == EXIT_SUCCESS;
}
~~~


~~~
> run_catch_test_reporter(c("A","-d yes"))
A completed in 1.5e-05s
===============================================================================
All tests passed (1 assertion in 1 test case)

[1] TRUE

> devtools::test()
Loading CatchTest
Testing CatchTest
C++ : .

DONE 
~~~

**Comment by kevinushey** [comment]
@Thell I think this should provide what you need: https://github.com/hadley/testthat/commit/daee2a56958095d8adddb340f38059995741cd3a

Let me know if that works!

**Comment by Thell** [comment]
@kevinushey :+1: 

Here's a cleaned up version of of the test runner providing full interactive usage...

~~~c++
//' @export
// [[Rcpp::export]]
bool test_cpp(Rcpp::CharacterVector args = "")
{
  args.insert(args.begin(), "catch");
  auto tmp = Rcpp::as<std::vector<std::string>>(args);
  std::vector<char*> argv;
  std::transform( tmp.begin(), tmp.end(), std::back_inserter(argv),
                  [](std::string& s){ return &s[0]; });

  auto& session = testthat::catchSession();
  const auto configData = session.configData();
  int return_code = session.run( (int)argv.size(), &argv[0]);
  session.useConfigData(configData);

  return return_code == 0;
}
~~~

I'm sure there's a more `R`ish way to handle getting the `argv`. If something was to write to the configData without restoring (I don't know what could) then rebuilding is the simplest cleanup. I gave a brief thought to storing the `configData` as a static and assigning when `session` initialized; but this works good for package building, so I'm happy for now. :)

Thanks!

**Comment by kevinushey** [comment]
Great, thanks!
