### ISSUE TITLE
No more inst/tests?

### ISSUE THREAD

**Issue by Thell** [hadley/testthat#337]
With the closing of Deprecate old style inst/tests #231, what's the recommended way to include/do tests for post install testing?

----

I ran across this while trying to implement a test setup similar to what many Rcpp based packages use with `runit` where `sourceCpp` can be an effective means of testing a package's api acessibility. ie.

`inst/tests/cpp/depends-support.cpp`
~~~c++
// [[Rcpp::plugins(cpp11)]]

// [[Rcpp::depends(RcppFoo)]]
#include <RcppFoo.h>

// [[Rcpp::export]]
bool builds_with_depends() { return true; }
~~~

or

`inst/tests/cpp/plugin-support.cpp`
~~~c++
// [[Rcpp::plugins(cpp11, RcppFoo)]]

#include <Rcpp.h>
#include <RcppFoo.h>

// [[Rcpp::export]]
bool builds_with_plugins() { return true; }
~~~

and then `sourceCpp` on those with a test following.

The only way I am able to do that now with `testthat` is by setting up dummy function and including the files as `@example` and then testing with a package check or `test_example`.

The other option is an external `RcppFooTest` package...

**Comment by hadley** [comment]
You'll have to tell people how to preserve the tests directory when installing a package (which I forget how to do :frowning: )

**Comment by jimhester** [comment]
@Thell `R CMD INSTALL --install-tests` will install the tests in `tests/`
