### ISSUE TITLE
problem with testthat and gmp package

### ISSUE THREAD

**Issue by stla** [hadley/testthat#341]
Hello, 

I'm using `testthat ‘0.11.0’` with Ubuntu and R `3.2.3`. 

This code, when I run it in the console, works fine:
```
  library(gmp)
  x <- as.bigz(matrix(1:12,3))
  expect_true(all(apply(x,1,min) == as.bigz(c(1,2,3))))
```

But when I run `devtools::test()` in my package with the following file, the first test fails:
```
context("test gmp")

test_that("this fails", {
  library(gmp)
  x <- as.bigz(matrix(1:12,3))
  expect_true(all(apply(x,1,min) == as.bigz(c(1,2,3))))
})

test_that("this works", {
  library(gmp)
  x <- as.bigz(matrix(1:12,3))
  expect_true(all(apply.bigz(x,1,min) == as.bigz(c(1,2,3))))
})
```
In the first test (`"this fails"`), the code runs `apply.default` instead of `apply.bigz`, here is the error message:
```
premier argument incorrect, doit être un tableau
```
in English:
```
incorrect first argument, must be an array
```

**Comment by stla** [comment]
It works if I do `importFrom(gmp,apply)`.  Is it expected ?

And I have a similar problem with `gmp` and `testthat` that I have not managed to solve.

**Comment by hadley** [comment]
Why are you loading the package in the test? Is it a suggested package?  Have you verified that gmp correctly exports the S3 method?

**Comment by stla** [comment]
It was an imported package when I posted this issue, but I intended to switch to a suggested package. I'm not sure to know how to verifiy that gmp correctly exports.

**Comment by stla** [comment]
There are strange things with this package.
In the console, this works fine:
```
>   library(gmp)
>   library(testthat)
>   x1 <- as.bigq(c(1/4, 3/4))
>   x <- matrix(as.bigq(c(1/4,3/4,1/2,1/2)), nrow=2, byrow=TRUE)
>   identical(x1, as.vector.bigq(x[1,])) # TRUE
[1] TRUE
>   expect_identical(x1, as.vector.bigq(x[1,]))
```
But this test fails:
```
test_that("weird", {
  library(gmp)
  x1 <- as.bigq(c(1/4, 3/4))
  x <- matrix(as.bigq(c(1/4,3/4,1/2,1/2)), nrow=2, byrow=TRUE)
  identical(x1, as.vector.bigq(x[1,])) # TRUE
  expect_identical(x1, as.vector.bigq(x[1,]))
})
```
Error:
```
1. Failure (at test-gmp2.R#12): weird ------------------------------------------
x1 is not identical to as.vector.bigq(x[1, ]). Differences: 
Lengths: 26, 2
Attributes: < target is NULL, current is list >
target is raw, current is bigq
```

**Comment by stla** [comment]
Since there are too many problems, I finally use this workaround:

```
test_that("My test", {
  aux <- "../../inst/local-tests/mytest.R"
  if(file.exists(aux)) source(aux, local=FALSE) else skip("skipped for R CMD Check")
  expect_.......
  expect_.......
  .......
})
```

**Comment by hadley** [comment]
If behaviour differs between console and `test()` it usually indicates a problem with the underlying code (i.e. it's making assumptions that are true when you run from the top-level in the console, but are not true in general)

**Comment by stla** [comment]
I spent a lot of time to figure out, but I really don't see what is going on. 
About your first comment, do you mean that any "`function.bigq`" should be exported by `gmp` ? For instance, ``` `[.big` ``` is not exported.

**Comment by hadley** [comment]
Yes, it should be exported as `S3method(`[`, big)`

**Comment by stla** [comment]
Ok, thanks. I will send the link of our discussion to the author.
