### ISSUE TITLE
Provide function to get path to test dir

### ISSUE THREAD

**Issue by hadley** [hadley/testthat#345]
So you can write code that can be run in `tests` and interactively.

**Comment by jennybc** [comment]
Related: nice solution for sourcing all `helper-` files for interactive test development? A separate issue?

**Comment by hadley** [comment]
@jennybc `source_test_helpers()`?

**Comment by jennybc** [comment]
I sure wish I had known about that sooner. I guess the function described here will make a nice default for the `path`.
