### ISSUE TITLE
report accurate line numbers for custom expect function failures

### ISSUE THREAD

**Issue by jackwasey** [hadley/testthat#347]
When testing a package with custom `expect_` functions using the `eval(bquote(.(x)` trick, with or without a custom `expectation`, the reported line number is of a nested call to `expect_that`, not the originating test.

`testthat:::find_test_srcref` has some nifty code to find the `expect_` calls in the testing frame, but of course any custom expectations are not found here. Work-around is to use `info = "something"` to identify the source of the error, but you might think it better to search back up the call stack outside of the `testthat` frames. Also, the work-around complicates the testing code unnecessarily, which overwhelms the simplification achieved by writing custom test functions in the first place.

Using your example from: http://r-pkgs.had.co.nz/tests.html#test-tests results in this behaviour in a package context.

**Comment by hadley** [comment]
Can you please provide a minimal reproducible?

**Comment by hadley** [comment]
I'm pretty sure this should now be fixed, or if not, it's now much easier to fix.
