### ISSUE TITLE
source helper scripts in test environment when running `test_file`

### ISSUE THREAD

**Issue by jackwasey** [hadley/testthat#350]
I have test harness data and functions in a `helper-base.R` file in `tests/testthat/`, and`test_file` seems to rely on this being `source`d manually, whereas `test_package` sets up a clean test environment.

Sourcing `helper-base.R` is a work-around, but pollutes the global environment, and I think it would be more consistent and simpler for `test_file` to source it for the user in a test environment.

**Comment by krlmlr** [comment]
Can you use `devtools::test(filter = "...")` or `testthat::test_package(filter = "...")`?

**Comment by jackwasey** [comment]
That's a good work-around, thanks for that. I think I'd still argue for `test_file` behaving in a similar way.

**Comment by hadley** [comment]
That sounds reasonable to me
