### ISSUE TITLE
control output/flooding on test errors

### ISSUE THREAD

**Issue by torbjorn** [hadley/testthat#351]
If I get a test error involving function arguments with big data sets, it ends up flooding my terminal with miles and miles of data matrices written to screen.

Could testthat do something smart, like making a data.table of it if its 2 dim for example.

T.

**Comment by hadley** [comment]
Please provide a reproducible example.

**Comment by hadley** [comment]
Oh, I think I fixed this incidentally

**Comment by torbjorn** [comment]
I'm struggling a bit to reproduce it, but it was with auto_test_package(), and I was running it from command line
