### ISSUE TITLE
Skip needs to capture context

### ISSUE THREAD

**Issue by hadley** [hadley/testthat#352]
I think we need something like:

```R
skip <- function(message, call = sys.call()) {
  cond <- structure(list(message = message, call = call), class = c("skip", "condition"))
  stop(cond)
}
```

**Comment by hadley** [comment]
And then we need a standard way of extracting the file name and line number from `skip()`, `error()` and `warning()`.

**Comment by hadley** [comment]
Looks like the context is lost if `call. = FALSE`:

```R
str(tryCatch({
  f <- function() stop("Hi!", call. = FALSE)
  f()
}, error = function(e) {
    e
    
  }
  
))
```

**Comment by krlmlr** [comment]
The context is available e.g. in our capture_calls() function, even with `call. = FALSE`. No need to modify skip(), we can simply install a handler here.

```
tryCatch(
  withCallingHandlers(
    stop("a", call. = FALSE),
    error = function(e) print(sys.calls())),
  error = function(e) NULL)
```

This would be also the way to go for #356: Simply call recover() in the calling handler (and use conditions for indicating test failues, https://github.com/hadley/testthat/issues/215#issuecomment-75367557).

**Comment by hadley** [comment]
@krlmlr ok, makes sense.
