### ISSUE TITLE
FR: DebugReporter

### ISSUE THREAD

**Issue by krlmlr** [hadley/testthat#356]
A reporter that interrupts the test with a `recover()` call at the first failed expectation. Implementation sketch:

```
DebugReporter <- setRefClass("DebugReporter", contains = "Reporter",
  methods = list(
    add_result = function(result) {
      if (!result$passed) {
        recover()
      }
    }
  )
)
```

Would be great to handle conditions, too (errors, warnings, skips; #343, #310), but to me this looks more difficult to implement.

**Comment by krlmlr** [comment]
On the other hand, if failures are special conditions (#215), this might be easier with `options(error = recover)`.

**Comment by hadley** [comment]
It feels like this is better attacked using `options(error = recover).`

**Comment by krlmlr** [comment]
This works for me with #360 and the following code in a test file, before the context() call:

```
library(testthat)
test_that <- function(name, code) {
  withr::with_dir("tests/testthat", code)
}
options(error = recover)
```

recover() is not the ideal choice here, because a bunch of calls to testthat's internals are included in the stack trace (cc @gaborcsardi). Also, remember to leave the debugger before restarting RStudio, otherwise the working directory remains set to tests/testthat.
