### ISSUE TITLE
Guaranteed order of a sequence of tests in a package

### ISSUE THREAD

**Issue by realAkhmed** [hadley/testthat#357]
In certain applications it is important to have a precise and guaranteed order of tests. For example, the test that is doing "test data import" should be done before the test that is verifying "the consistency of imported data".

It looks like the key function here is [`find_test_scripts`](https://github.com/hadley/testthat/blob/6cdd17cab674175297e16e12ac5ed29266534390/R/test-files.r#L76) which does not seems to guarantee a particular order of files. (does `dir` guarantee the same sort order across different platforms?)

Does it make sense to return `sort(files)` instead of [`files`](https://github.com/hadley/testthat/blob/6cdd17cab674175297e16e12ac5ed29266534390/R/test-files.r#L91) in order to make sure that the order of tests is deterministic and predictable? or does `dir` already do that in a cross-platform-safe manner?

**Comment by krlmlr** [comment]
From `?dir`:

> The files are sorted in alphabetical order, on the full path if full.names = TRUE.

Not sure about the locale, though. If you want to be locale-independent, you'd need something like `withr::with_locale("C", ...)`, but this shouldn't make a difference if your file names contain letters and digits only.

**Comment by realAkhmed** [comment]
Thanks @krlmlr !

My concern was two-fold:

1. Current performance:
    - this is regarding issues like platform-independence (say, case-sensivity: would "a","A","b","B" be the correct order or "A","a","B","b" or "A","B","a","b" or case-insensitive etc)
1. Future performance:
   - The future intent in the code was not clear to me: sorting emerges as an artifact of `dir`, would someone later step in and break the sorting with some new feature? 

If 1) is not a concern above, this may not even need a change to `sort(files)`. 2) could be done with just one more unit test verifying that sorting of the file list in `find_test_scripts` is equal to expected.

**Comment by hadley** [comment]
This isn't important to me, but I'd be happy to review a PR.
