### ISSUE TITLE
expect_equal gives misleading error message for equivalent objects

### ISSUE THREAD

**Issue by richierocks** [hadley/testthat#361]
If the actual and expected values are equivalent but not equal, then the failure message from `expect_equal` is misleading: it seems like a floating point rounding problem.

```{r}
expect_equal(c(a = 1), 1)
## Error: c(a = 1) not equal to 1
## 1 - 1 == 0
```

When this expectation has failed, `all.equal` should be a character vector describing the problems.  It might be more informative to print these as well.  In this case, the output I'm suggesting would be:

```
## Error: c(a = 1) not equal to 1
## 1 - 1 == 0
## names for target but not for current
```

Very loosely related: https://github.com/hadley/testthat/issues/339

**Comment by hadley** [comment]
Fixed as part of my rewrite of the compare methods:

```R
expect_equal(c(a = 1), 1)
#> Error: c(a = 1) not equal to 1
#> names for target but not for current 
```

**Comment by daf** [comment]
Could someone please explain what

> `## names for target but not for current`

means?  I don't know what `names`, `target`, or `current` refers to.  I'm able to pass tests if I change it to use `expect_match` with the full character vector, but I'm trying to learn why I can't use `expect_identical`/`expect_equal`.

**Comment by gaborcsardi** [comment]
`target` is the expected result, `current` is the actual result. `target` has names, `current` does  not. E.g. 

```r
❯ library(testthat)

❯ expect_equal("a", c(x="a"))
Error: "a" not equal to c(x = "a").
names for current but not for target

❯ expect_identical("a", c(x="a"))
Error: "a" not identical to c(x = "a").
names for current but not for target

❯ expect_equal("a", unname(c(x="a")))

❯ expect_identical("a", unname(c(x="a")))
```
