### ISSUE TITLE
Allow matching multiple lines of output in expect_output

### ISSUE THREAD

**Issue by richierocks** [hadley/testthat#362]
For testing functions that write content to a file, the easiest to way to test them is (I think) to write to stdout and check that the lines of output are what you expected.  This avoids any worries about write permissions and cleaning up afterwards.

Currently `expect_output` only allows you to match a single regexp so you have to have a test like:

```{r}
test_that(
  "my_write_fn write to stdout",
  {
    expected <- c("line1", "line2")
    actual <- capture.output(my_write_fn(some_input)) 
    expect_equal(actual, expected)
  }
)
```

I think it would be more natural if you could write a test like:

```{r}
test_that(
  "my_write_fn write to stdout",
  {
    expected <- c("line1", "line2")
    expect_output(my_write_fn(some_input), expected)
  }
)
```

**Comment by hadley** [comment]
Hmmm, I think it would be most natural to write to a temp file.
