### ISSUE TITLE
Support Catch CHECK_THROWS for C++ level error testing

### ISSUE THREAD

**Issue by richierocks** [hadley/testthat#365]
The [Catch documentation](https://github.com/philsquared/Catch/blob/master/docs/assertions.md) suggests that you can test for exceptions using `CHECK_THROWS`, or `CHECK_THROWS_AS`.  As far as I can tell, these aren't yet supported in *testthat*.

cc @kevinushey

**Comment by kevinushey** [comment]
You should be able to use the built-in Catch macros as-is (although with the `CATCH_` prefix); the `testthat` ones are added just for convenience.

Perhaps we can add some mapping for this, e.g.

    expect_throws() --> CHECK_THROWS
    expect_throws_as() --> CHECK_THROWS_AS

Thoughts?

**Comment by richierocks** [comment]
To have syntax closest to standard `testthat` code, I'd recommend an overloaded `expect_error`:

```
expect_error(expr, exception_type) --> CHECK_THROWS_AS
expect_error(expr) --> CHECK_THROWS
```

But if overloading is too much of a faff, your solution is also fine.

**Comment by kevinushey** [comment]
Overloading would be nice, but unfortunately that's a C++11-ism (strictly speaking, C++98 doesn't have variadic macros, even though all real compilers have them ...)
