### ISSUE TITLE
Think about return value for expect() and expect_...()

### ISSUE THREAD

**Issue by krlmlr** [hadley/testthat#367]
Currently, the expectation is returned invisibly. In some cases it would be useful to get access to the object tested. For instance, we might want to check that an expression gives a warning *and* returns a certain value.

In any case, this seems to require storing the object under test in the expectation object:

```r
expectation <- function(object, ...) {
   structure(list(object = object, ...), class = "expectation")
}
```

**Comment by hadley** [comment]
Yeah, I think the principle should be that all expectations invisibly return the first argument so you can pipe if you choose to. (I think the general principle is that any function called primarily for side-effects should invisibly return the first argument). That doesn't allow for testing for (e.g.) a warning and the output, but it does get one step closer.
