### ISSUE TITLE
if a helper file is changed, auto_test_package should re-run tests

### ISSUE THREAD

**Issue by jackwasey** [hadley/testthat#376]
Currently, auto_test_package notices that the helper-* files have changed, and appears to source them, but doesn't run any tests. It would be clever if the dependencies between the contents of the helper files and the tests could be inferred, but at a first approximation, all tests should be re-run.

**Comment by hadley** [comment]
I'd be happy to review a PR for this, but since I don't use the autotest stuff, I'm not going to implement it
