### ISSUE TITLE
Check output, message, warning, error in a single function

### ISSUE THREAD

**Issue by krlmlr** [hadley/testthat#384]
`expect_side_effects <- function(object, output = NULL, message = NULL, warning = NULL, error = NULL, file = NULL)`

This new function could then power the existing expect_(output|message|warning|error|silent)() functions.

If a file argument is given, then all output is collected and compared with file contents; the file is overwritten with the new contents.

Follow-up to https://github.com/hadley/testthat/pull/379#issuecomment-190721317.

**Comment by hadley** [comment]
If we're going to do something new, I'd rather it would be pipeable. That suggests wrapping the call `evaluate_promise()` and adding infrastructure to easily do tests of that object.

**Comment by krlmlr** [comment]
Very generic approach: A `transform` or `mutate` argument to all expect_() functions.

```
expect_match(., "output-regex", transform = .$output)
```

**Comment by hadley** [comment]
Another approach would be to use the T-pipe:

```R
evaluate_promise(...) %T>%
   {expect_match(.$error, ...)} %T>%
   {expect_match(.$warings, ...)}
```

But that's rather ugly.

**Comment by krlmlr** [comment]
Looks good still.
