### ISSUE TITLE
Make context and test part of "expectation" class

### ISSUE THREAD

**Issue by krlmlr** [hadley/testthat#386]
so that `add_result = function(result) { ... }`, to support easier aggregation of results (https://github.com/hadley/testthat/pull/380#issuecomment-190853256).

**Comment by hadley** [comment]
I like the idea of formalising these as fields in the expectation class (I think I'm informally tacking them on at the moment).  But I do like the current symmetry of the reporter callbacks where as you get more and more detailed you get more and more arguments.

**Comment by krlmlr** [comment]
It's not terribly important anymore, and the reporter is a beautiful peace of ASCII art indeed:

```
  public = list(
    start_reporter = function() {},
    start_context =  function(context) {},
    start_test =     function(context, test) {},
    add_result =     function(context, test, result) {},
    end_test =       function(context, test) {},
    end_context =    function(context) {},
    end_reporter =   function() {}
  )
```
