### ISSUE TITLE
consider un-deprecating `info` (and `label`?) for certain expectations

### ISSUE THREAD

**Issue by kevinushey** [hadley/testthat#392]
E.g. `expect_true(foo, "what went wrong")` seems a common pattern. (What was the motivation for deprecating the two fields?)

**Comment by hadley** [comment]
Two reasons:

* They add quite a lot of complexity to the code

* In most cases (apart from `expect_true()`/`expect_false()`) you'd be better off using metaprogramming to actually make the expression you wanted to test.

* I'd rather invest effort in general metaprogramming tools.

That said, the current approach seems a bit aggressive, and is likely to cause a lot of pain. I think it's probably better to soft-deprecate for now.

**Comment by kevinushey** [comment]
Thanks! Agree that soft-deprecation is better.
