### ISSUE TITLE
expect_output fails without explicit print

### ISSUE THREAD

**Issue by vspinu** [hadley/testthat#399]
With lubridate I am getting a bunch of errors with new testthat which were not occurring before. 

This is one of them:

```
> expect_output("aa", "aa")
Error: `output` does not match "aa".
Actual value: ""
```

This used to work before, now an explicit print is required:

```
  expect_output(print("aa"), "aa")
```

**Comment by hadley** [comment]
Yes, this is by design.

**Comment by vspinu** [comment]
I thought so. It could be nice to add this to the NEWS.md.

**Comment by hadley** [comment]
Sorry, I could've sworn it was there. I must have accidentally dropped it while rewriting.
