### ISSUE TITLE
'label' parameter is no more supported in some expect_...()

### ISSUE THREAD

**Issue by sgsokol** [hadley/testthat#402]
I used the following expression in a loop :

```
expect_more_than(sum(i), 0, label=sprintf("length of central diff for %s", format1(test))
```

but with the current version of testthat an error is thrown:
unused argument (label = "length of central diff for x^2")

**Comment by hadley** [comment]
Thanks. A minimal reprex is:

```R
expect_more_than(1, 2, label = "MY LABEL")
```
