### ISSUE TITLE
Problem with auto_test() in version 0.11.0.9000

### ISSUE THREAD

**Issue by stibu81** [hadley/testthat#405]
This [question](http://stackoverflow.com/q/35897164/4303162) on StackOverflow describes an issue with `auto_test()` that was not present in testthat 0.11.0.

Create the following files:

code/src/add.R:

    add <- function(x,y){
        x+y
    }

code/test/test-add.R:

    library(testthat)

    test_that("adding numbers", {
        expect_equal(add(2,3), 5)
        expect_equal(add(5,5), 10)
    })

The following gives an error:

    library(testthat)
    auto_test('code/src', 'code/test')
    ## Error in find_reporter(reporter) : attempt to apply non-function

**Comment by hadley** [comment]
Did you load testthat?

**Comment by stibu81** [comment]
Yes, I did. I made that clear now in my original post.

**Comment by hadley** [comment]
Are you sure that's the error you get...

**Comment by pschloss** [comment]
I was the OP over at SO and this is the error I was getting for the Repo version of testthat...

````
> auto_test('code/src', 'code/test')
Error in find_reporter(reporter) : attempt to apply non-function
````

When I installed the CRAN version it worked.

**Comment by stibu81** [comment]
Of course, I'm not sure! I just changed my original post again. And you also have the error message posted by pschloss. I switched back and forth between the two versions and made a mess. Sorry about that.
