### ISSUE TITLE
Should empty test_that throw a skip?

### ISSUE THREAD

**Issue by hadley** [hadley/testthat#413]
So it's easy to notice when you've forgotten to add an expectations

**Comment by gaborcsardi** [comment]
I used to put code in `test_that` without any expectations, just to make sure that it runs. This was before `expect_silent()`. Sometimes I put in an `expect_true(TRUE)` at the end, just to see some output, sometimes not.

Anyway, a skip is not an error, just a mild message, and I agree it could be useful.
