### ISSUE TITLE
default environment for source_test_helpers()

### ISSUE THREAD

**Issue by jennybc** [hadley/testthat#415]
The default environment for `source_test_helpers()` changed from the [global environment](https://github.com/hadley/testthat/blob/cdb875c1943f0bee3d8d0366aaad8ce92ad62430/R/test-files.r#L63-L65) to the [test environment](https://github.com/hadley/testthat/blob/a102b89a8f23120ea5e614a1adf229b947e14850/R/source.R#L40-L42). This is noticeable when I step through test files interactively. Unless I do `source_test_helpers(..., env = globalenv())`, nothing I define in my helper files is actually available.

I liked the old way better, but maybe there are good reasons for the change? In which case, this would be good to put into `NEWS.md`.

**Comment by hadley** [comment]
The point was to make it consistent with the other `source_*()` functions. But I now think your problem should be resolved by devtools - could you please file an issue there? (if you haven't already)
