### ISSUE TITLE
mixing different environments containing data

### ISSUE THREAD

**Issue by shug0131** [hadley/testthat#417]
I'm developing a package that uses formula-style arguments. I copied the opening lines from the lm() function to create data frame that contains all the variables, from wherever they live. This works, but not in test_that(). The code illustrates the problem, using lm

```
test_that("first basict fit with mixed data sources",{
  propX <- with(immdef, 1-xoyrs/progyrs)
  #fit <- rpsftm(progyrs, censyrs, propX,imm,immdef, 
  #         lowphi=-1, hiphi=1)
  lm(progyrs~propX, data=immdef)
})
```

It works ok if I do it line by line to the terminal. When I use the "test package" tool in Rstudio the output is

```
==> devtools::test()

Loading rpsftm
Loading required package: testthat
Testing rpsftm
Test for desired errors in rpsftm : ....
Test the rpsftm() function Hello : 
first fit : 
with no data argument at all : Error in eval(expr, envir, enclos) : object 'propX' not found
Calls: <Anonymous> ... rpsftm -> eval -> eval -> <Anonymous> -> eval -> eval
Execution halted

Exited with status 1.
```

**Comment by hadley** [comment]
I don't think you should assume that `lm()` does it correctly.

**Comment by shug0131** [comment]
My point is that the code works fine when I run it line by line (as does lm()). When I enclose it in test_that() it fails.

**Comment by hadley** [comment]
And my point is that that doesn't imply that testthat is wrong.

**Comment by shug0131** [comment]
I've now partially educated myself on the area of R environments and
thus fixed this. I think. Your web page on R programming was absolutely
crucial there. Thanks!

 

I  concluded that a formula object has an environment attached, and that
this needs to be the correct one to use model.frame() and update(). I
needed to explicitly set the environment in my code. 

 

The documentation on these topics is very circular, and particularly the
formula object, doesn't have anything saying what it actual is. Nor
_why_ it is the way it is. If you know any documents in that area to
learn more, maybe from a historical perspective, I'd find it helpful,
and it might compliment your webpage well?  Also I found myself
wondering how does R know magically that the object returned from a
function argument like "formula=~1", is a formula?

 

Simon 

 

Dr Simon Bond MA PhD CStat CSci

Senior Statistician

Tel: (+44) (0)1223 596475 | Ext 6475| simon.bond@addenbrookes.nhs.uk
<mailto:XXXX.XXXXXX@addenbrookes.nhs.uk> | www.cuh.org.uk/cctu

**Comment by hadley** [comment]
I'd read <https://developer.r-project.org/nonstandard-eval.pdf> for a historical perspective (although somewhat incomplete), and <http://rpubs.com/hadley/lazyeval> for my latest thoughts (although there are going to be quite a few changes that I haven't incorporated yet)

**Comment by shug0131** [comment]
Thanks. Both those were very helpful

 

Simon 

 

Dr Simon Bond MA PhD CStat CSci

Senior Statistician

Tel: (+44) (0)1223 596475 | Ext 6475| simon.bond@addenbrookes.nhs.uk
<mailto:XXXX.XXXXXX@addenbrookes.nhs.uk> | www.cuh.org.uk/cctu
