### ISSUE TITLE
"global" variable which can be used for all tests

### ISSUE THREAD

**Issue by Christoph999** [hadley/testthat#422]
Is there a way to assign a global variable in the beginning of the test? Thus, all testthat could use it. Or would that be against the policy that each testthat creates its own (clean) environment?
Thanks for the information.

**Comment by krlmlr** [comment]
You can create these in the "helper" files (R scripts that live in tests/testthat, name starts with "helper-"). These are executed once for each test run.

**Comment by Christoph999** [comment]
Cool, works already. Thanks a lot!

**Comment by lynxoid** [comment]
There's very little documentation on helpers in the [testthat 1.0.2 docs](https://cran.r-project.org/web/packages/testthat/testthat.pdf) -- are they covered somewhere else perhaps?
