### ISSUE TITLE
expectations not wrapped in 'test_that()' call don't get reported

### ISSUE THREAD

**Issue by kevinushey** [hadley/testthat#427]
Not sure if this is intended or not, but I noticed that with the current development version of `testthat` tests are not reported (e.g. with the little `.`) when not wrapped in `test_that()`.

Is this a regression or intended behavior?

---

Repro:

``` sh
cd $TMPDIR
rm -rf hellotestthat
R -e 'devtools::create("hellotestthat")'
cd hellotestthat
R -e 'devtools::use_testthat()'
echo -e 'context("Hello")\nexpect_true(TRUE)\n' > tests/testthat/test-hello.R
R -e 'devtools::test()'
```

With old testthat:

```
> devtools::test()
Loading hellotestthat
Loading required package: testthat
Testing hello
Hello : .

DONE
```

New testthat:

```
> devtools::test()
Loading hellotestthat
Loading required package: testthat
Testing hello
Hello:

DONE ===========================================================================
```

**Comment by hadley** [comment]
Definitely a regression :/

**Comment by kevinushey** [comment]
It looks like the problem is that all of the reporter handling only gets registered in the `test_code` function: 

https://github.com/hadley/testthat/blob/94fc45a2e9b92168d0f74328bcfaad66108daaaf/R/test-that.R#L76-L89

Does it make sense to move this registration code into e.g. `test_file`?

**Comment by krlmlr** [comment]
The current code makes sure that errors and skips do not propagate beyond the test_that() block. I guess we need a second, thinner withCallingHandlers() in test_file() (and probably elsewhere) if we want the dots in "bare" expectations.
