### ISSUE TITLE
expect_ functions

### ISSUE THREAD

**Issue by MansMeg** [hadley/testthat#428]
Hi!

Thanks for a great package! I relied heavily on the old format to create my own expecttations. In the new version it seems like there is a function called ```expect``` that is used by all other expectations. But this function is not experted to the package API. How should I implement my own expectations in version 0.12, any suggestions?

**Comment by MansMeg** [comment]
Sorry, didnt check the news.md.

**Comment by hadley** [comment]
You can also call `succeed()` and `fail()`

**Comment by MansMeg** [comment]
Thanks. I've now read the news.md but it is not obvious exactly how to do this. Is the intention to make ```expect()``` a formal exported funcation, part of the package api, or should I only use ```succeed``` and ```fail```? I'm not very keen on using non-exported functions. =)

**Comment by hadley** [comment]
I don't want to export expect yet, so use succeed and fail.

**Comment by krlmlr** [comment]
You could also use expect_true(), as suggested in the very first item of NEWS.md .
