### ISSUE TITLE
expect_silent missing info field?

### ISSUE THREAD

**Issue by MansMeg** [hadley/testthat#429]
Hi!
I write loops testing using expect_silent(). I miss the info field. =)

**Comment by hadley** [comment]
I'm not convinced that these info fields are a good idea (or at least the current approach isn't the best one). I'd prefer not to add `info` arguments to random expectations until it's clear that I really do want to follow this approach.

(That said, I'd be happy to review a PR that added an `info` field to `expect_silent()`)
