### ISSUE TITLE
expect_list throws error

### ISSUE THREAD

**Issue by kerschke** [hadley/testthat#433]
Similarly to the previous issue, I also get an error when applying `expect_list` to a list.

```{r}
> mylist = list(a = 2, b = c("hello", "world"))
> expect_list(mylist)
Error in testthat::expectation(identical(res, TRUE), failure_msg = res,  : 
  unused arguments (failure_msg = res, success_msg = "all good")
```

**Comment by hadley** [comment]
I don't know where these functions are defined - they're not part of testthat.

**Comment by mllg** [comment]
They are defined in checkmate. The next update of `testthat` will break the implemented `expect_*` extensions, c.f. https://github.com/mllg/checkmate/issues/63. Apparently, the changes to `expectation()` already causes trouble on some CIs.

Is there a future-proof way to create custom expectations? Is there an ETA for the next CRAN update?

**Comment by hadley** [comment]
You'll need to talk to the maintainer of checkmate - I've notified the maintainers of all reverse dependencies several weeks ago. Testthat is scheduled for release on April 4

**Comment by mllg** [comment]
I'm the maintainer of checkmate. Did you also send a notice to reverse suggests? I must have missed it. I'll prepare try to adept checkmate to the new version ASAP.

**Comment by hadley** [comment]
@mllg R CMD check on checkmate passed without any problems, so you didn't get a notification.
