### ISSUE TITLE
Label lookup does not work if expect_identity is called from a helper function

### ISSUE THREAD

**Issue by mllg** [hadley/testthat#435]
Here is a minimal package to demonstrate the issue: <https://github.com/mllg/test-testthat>

**Comment by hadley** [comment]
Can you please create an inline reproducible example?

**Comment by mllg** [comment]
In this case: nope. This is only reproducible if the function which calls `expect_identity()` is defined in a second file `helper.R`. I guess the environment of the function is stripped away which somehow breaks `lazy()` in `make_label()`.

**Comment by hadley** [comment]
Minimal reprex is 

```R
test_many = function(x) {
  expect_true(x)
  expect_identical(x, TRUE)
}
test_many(TRUE)
```

Doesn't need to be in a separate file for me.
