### ISSUE TITLE
expect_success and expect_failure defunct

### ISSUE THREAD

**Issue by mllg** [hadley/testthat#436]
As far as I understand the documentation, this should work:

```r
expect_success(expectation("success", message = "foo"))
expect_failure(expectation("failure", message = "foo"))
```

Problem is probably here: <https://github.com/hadley/testthat/blob/master/R/expect-self-test.R#L45> where you return `NULL` instead of the expectation.

**Comment by hadley** [comment]
No - you need to call `expect()` to actually trigger the expectation.
