### ISSUE TITLE
auto_test_package keeps printing failure messages of passing tests that failed previously

### ISSUE THREAD

**Issue by nealrichardson** [hadley/testthat#441]
The watcher (`auto_test_package`) seems to be holding onto failure messages even after the tests pass again. With a toy package and file "tests/testthat/test-something.R", containing:

    context("A test")

    test_that("true is true", {
        expect_true(TRUE)
    })

I fired up R and started watching:

    $ R
    > library(testthat)
    > auto_test_package("../testpackage/")
    Loading testpackage
    A test: .

    DONE ===========================================================================

I then added the second expectation `expect_false(TRUE)`. Oops! Correctly, the test failed:

    Rerunning tests:  test-something.R 
    Warning: 'devtools::with_envvar' is deprecated.
    Use 'withr::with_envvar' instead.
    See help("Deprecated") and help("devtools-deprecated").
    A test: .1

    Failed -------------------------------------------------------------------------
    1. Failure: true is true (@test-something.R#5) ---------------------------------
    TRUE isn't false.

    DONE ===========================================================================

I fixed my test: `expect_false(FALSE)`. The watcher re-ran the tests, saw that they passed, but it printed the failure message again:

    Rerunning tests:  test-something.R 
    Warning: 'devtools::with_envvar' is deprecated.
    Use 'withr::with_envvar' instead.
    See help("Deprecated") and help("devtools-deprecated").
    A test: ..

    Failed -------------------------------------------------------------------------
    1. Failure: true is true (@test-something.R#5) ---------------------------------
    TRUE isn't false.

    DONE ===========================================================================

This is running with the latest `testthat` from GitHub. 

    > sessionInfo()
    R version 3.2.4 Patched (2016-03-16 r70355)
    Platform: x86_64-apple-darwin13.4.0 (64-bit)
    Running under: OS X 10.11.3 (El Capitan)

    locale:
    [1] C/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

    attached base packages:
    [1] stats     graphics  grDevices utils     datasets  methods   base     

    other attached packages:
    [1] testpackage_0.1.0 testthat_0.11.0.9000 

    loaded via a namespace (and not attached):
     [1] magrittr_1.5    R6_2.1.2        tools_3.2.4     withr_1.0.0    
     [5] roxygen2_5.0.1  Rcpp_0.12.3     memoise_1.0.0   crayon_1.3.1   
     [9] stringi_1.0-1   stringr_1.0.0   digest_0.6.9    devtools_1.10.0

**Comment by krlmlr** [comment]
I'm seeing this too. Probable reason: The clone() call in auto_test...() doesn't properly clone the failures, skips, and warnings members of the SummaryReporter, because they are initialized as environments.
