### ISSUE TITLE
trouble using test_path() with expect_equal_to_reference()

### ISSUE THREAD

**Issue by jennybc** [hadley/testthat#448]
Seems like this should work. But `test_path()` doesn't want to make a path that doesn't (yet) exist.

``` r
library(testthat)
dir(test_path(), pattern = "\\.rds")
#> character(0)
expect_equal_to_reference(1, "tests/testthat/one.rds")
dir(test_path(), pattern = "\\.rds")
#> [1] "one.rds"
file.remove(test_path("one.rds"))
#> [1] TRUE
dir(test_path(), pattern = "\\.rds")
#> character(0)
expect_equal_to_reference(1, test_path("one.rds"))
#> Error: `tests/testthat/one.rds` doesn't exist
```

**Comment by jennybc** [comment]
I now see "An error will be thrown if the path doesn't exist." in the help file. OK. But isn't this one of the main uses for `test_path()`?

**Comment by krlmlr** [comment]
I agree that testing if the file exists shouldn't be the responsibility of test_path(). Removing the check and amending the documentation seems fair to me.
