### ISSUE TITLE
try_again wrapping a test_that fails when called from a file

### ISSUE THREAD

**Issue by rdiaz02** [hadley/testthat#454]
I think a construction like

```
try_again(3, 
    test_that("something", {
        code_in_here
        expect_something(blablabla)
    })
)
```

doesn't work if that is called such as `test_file("some_file.R")` or from automated testing: the testing does not actually repeat (i.e., we get a failure reported as soon as the expectation is not fulfilled, without any additional iterations). So I think I am misunderstanding some of the use cases of `try_again`.

This is an example that works as I expect (i.e., it tries three times, and succeeds) when run interactively but will fail when you save it as a file and do `test_file()`

```
## The third is > 0.5
set.seed(1)
runif(3)

set.seed(1)
try_again(3,
          test_that("runif > 0.5", {
              x <- runif(1)
              cat("\n x is ", x, "\n")
              expect_true(x > 0.5)
          })
          )

```

**Comment by hadley** [comment]
Yeah, this is out of scope for `try_again()`. It's designed to wrap around individual expectations
