### ISSUE TITLE
test_that breaks capture.output(type = "message")

### ISSUE THREAD

**Issue by mllg** [hadley/testthat#460]
MWE:

``` r
test_that("capture.output", {
expect_true(length(capture.output(message("foo"), type = "message")) == 1)
})
```

Session info:

```
R version 3.2.4 (2016-03-10)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.11.4 (El Capitan)

locale:
[1] de_DE.UTF-8/de_DE.UTF-8/de_DE.UTF-8/C/de_DE.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] testthat_1.0.0 setwidth_1.0-4

loaded via a namespace (and not attached):
[1] magrittr_1.5  R6_2.1.2      memoise_1.0.0 crayon_1.3.1  digest_0.6.9
```

**Comment by krlmlr** [comment]
All messages are muffled. Does expect_message() work for your use case?

**Comment by mllg** [comment]
I do not want to check for output, but my function internally relies on `capture.output()` to store the output of an arbitrary user-provided expression. According to the documentation multiple nested diversions via `sink()` should be supported.

**Comment by krlmlr** [comment]
sink() is not used to divert the messages, the "muffleMessage" restart is invoked. You can override the behavior by providing your own message handler:

```
test_that("capture.output", {
  o <- withCallingHandlers(
    capture.output(message("foo"), type = "message"),
    message = function(e) cat(conditionMessage(e), file = stderr(), sep = ""))
  expect_true(length(o) == 1)
})
```

**Comment by krlmlr** [comment]
Maybe we should export that pattern in a new function `enable_messages()`?

```r
test_that("capture.output", {
  o <- enable_messages(capture.output(message("foo"), type = "message"))
  expect_true(length(o) == 1)
})
```

**Comment by hadley** [comment]
@mllg could you provide a bit more context? i.e. why are you using `capture.output()` to capture messages in your real code?

**Comment by hadley** [comment]
Reprex to confirm this only affects messages:

``` r
library(testthat)

test_that("x", expect_length(capture.output(message("foo"), type = "message"), 1))
#> Error: Test failed: 'x'
#> * capture.output(message("foo"), type = "message") has length 0, not length 1.
test_that("x", expect_length(capture.output(print("foo")), 1))
```

**Comment by mllg** [comment]
> @mllg could you provide a bit more context? i.e. why are you using capture.output() to capture messages in your real code?

This came up in https://github.com/mllg/batchtools where the user provides a function which is evaluated on a remote system. `capture.output()` is used to capture stdout/stderr and store it in a log file.

**Comment by hadley** [comment]
Unfortunately I don't see any way to work around this, and it affects a very small proportion of users so I'm going to close. If anyone comes up with a simple approach, I'd be happy to review a PR.
