### ISSUE TITLE
skip_if_not_rstudio

### ISSUE THREAD

**Issue by sfr** [hadley/testthat#462]
Method [skip_if_not_rstudio](https://github.com/rstudio/rstudioapi/blob/master/tests/testthat/helper-rstudio.R) from [rstudioapi](https://github.com/rstudio/rstudioapi) could be one of the testthat's `skip*` methods.

**Comment by hadley** [comment]
But tests are rarely run inside RStudio - normally they're run in a separate R process.

**Comment by sfr** [comment]
Unless you are developing RStudio addins. But generally I agree.

**Comment by kevinushey** [comment]
For what it's worth, a simple way of detecting this locally would be with something like:

```
if (!is.na(Sys.getenv("RSTUDIO", unset = NA))) skip("Not RStudio")
```
