### ISSUE TITLE
Unable to load shared object `testthat.so` during installation

### ISSUE THREAD

**Issue by joelostblom** [hadley/testthat#463]
Hi,
I am having some troubles installing the `testthat` package. I tried two different approaches and get the same error message:

In:
```
install_packages('testthat')
```

Out:
```zsh
** testing if installed package can be loaded
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/home/joel/anaconda3/lib/R/library/testthat/libs/testthat.so':
  /home/joel/anaconda3/lib/R/library/testthat/libs/testthat.so: undefined symbol: _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEED1Ev
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/home/joel/anaconda3/lib/R/library/testthat’
```

In:
```
dev_mode(on=T)
install_github('hadley/testthat')
```

Out:
```bash
** testing if installed package can be loaded
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/home/joel/R-dev/testthat/libs/testthat.so':
  /home/joel/R-dev/testthat/libs/testthat.so: undefined symbol: _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEED1Ev
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/home/joel/R-dev/testthat’
```

Any ideas of how I can get around this?

I am running R 3.2.2 via anaconda on Antergos (Arch derivative), with kernel 4.5.0-1-ARCH.

**Comment by joelostblom** [comment]
I had missed that `testthat` is available in the conda repositories. Running `conda install -c r r-testthat` installed the packaged successfully.

**Comment by kevinushey** [comment]
FWIW, based on the error message, I can only guess that you don't have the requisite C++ standard library installed on your system, or it's not being linked to on compilation, or it's missing that symbol for some reason. (Maybe you need to compile in C++11 mode?)
