### ISSUE TITLE
Calling `test_dir` inside of `test_that` can silently fail

### ISSUE THREAD

**Issue by nealrichardson** [hadley/testthat#468]
While working on https://github.com/hadley/testthat/pull/467, I noticed that the expectations in test-reporter-tap.R weren't being evaluated. Pulling the `test_dir` outside of the `test_that` block made the expectations run (and fail). I did a little more investigation, and I found a few things:

A. Running this:

```
context("test_dir inside test_that")

test_that("testing the test_dir", {
  test_dir("test_dir", reporter="tap")
  expect_true(FALSE)
})
```

yields

```
test_dir inside test_that: 1..2
# Context Bare
ok 1 testing the test_dir
not ok 2 testing the test_dir
  attempt to apply non-function
  1: test_dir("test_dir", reporter = "tap") at testthat/test-test-dir.R:9
  2: test_files(paths, reporter = reporter, env = env, ...)
  3: with_reporter(reporter = current_reporter, results <- lapply(paths, test_file, env = env, 
         reporter = current_reporter, start_end_reporter = FALSE, load_helpers = FALSE))
  4: force(code)
  5: lapply(paths, test_file, env = env, reporter = current_reporter, start_end_reporter = FALSE, 
         load_helpers = FALSE)
  6: FUN(X[[i]], ...)
  7: with_reporter(reporter = reporter, start_end_reporter = start_end_reporter, {
         lister$start_file(basename(path))
         source_file(path, new.env(parent = env), chdir = TRUE)
         end_context()
     })
  8: force(code)
  9: source_file(path, new.env(parent = env), chdir = TRUE)
  10: eval(exprs, env)
  11: eval(expr, envir, enclos)
  12: expect_that(1, equals(1)) at test_dir/test-bare-expectations.R:3
  13: condition(object)
  14: expect_equal(x, expected, ..., expected.label = label)
  15: expect(comp$equal, sprintf("%s not equal to %s.\n%s", lab_act, lab_exp, comp$message), 
         info = info)
  16: withRestarts(if (expectation_broken(exp)) {
         stop(exp)
     } else {
         signalCondition(exp)
     }, continue_test = function(e) NULL)
  17: withOneRestart(expr, restarts[[1L]])
  18: doWithOneRestart(return(expr), restart)
  19: signalCondition(exp)
  20: (function (e) 
     {
         register_expectation(e, frame + 11, sys.nframe() - 6)
         invokeRestart("continue_test")
     })(structure(list(message = "1 not equal to 1.\nEqual\n", srcref = NULL), .Names = c("message", 
     "srcref"), class = c("expectation_success", "expectation", "condition")))
  21: register_expectation(e, frame + 11, sys.nframe() - 6)
  22: get_reporter()$add_result(context = get_reporter()$.context, test = test, result = e)
  23: o_apply(self$reporters, "add_result", context = context, test = test, result = result)
  24: lapply(objects, function(x) x[[method]](...))
  25: FUN(X[[i]], ...)
  26: x[[method]](...)
```

All of the tests in "test_dir" were not run, and the `expect_true(FALSE)` was not hit either. And the contents of the TAP output from the test_dir call are contaminated by the description of the `test_that` that encloses it.

B. Wrapping `test_dir` in `capture.output` prevents the failure but skips further execution. This was why the expectations in test-reporter-tap.R weren't running but weren't failing like above.

Executing this

```
context("test_dir inside test_that")

test_that("testing the test_dir", {
  output <- capture.output(test_dir("test_dir", reporter="tap"))
  expect_true(FALSE)
})
```

shows no expectations running at all, including no `FALSE isn't true.` I saw https://github.com/hadley/testthat/issues/460 and wondered if it was potentially related.

C. Running the existing tests for `test_dir` in https://github.com/hadley/testthat/blob/master/tests/testthat/test-test_dir.R, I see only two expectations passing. It appears that the first test block bails out before L34 runs, but the other two expectations are executed, as confirmed by adding `expect_true(FALSE)` after all three and seeing which failed. So it appears that there are conditions under which test_dir can be called successfully from inside test_that.

**Comment by krlmlr** [comment]
There should be no silent failures as of #474, could you please try again?

**Comment by nealrichardson** [comment]
Yep, LGTM now. I'll close this. Thanks!
