### ISSUE TITLE
system.file cannot be mocked

### ISSUE THREAD

**Issue by lbartnik** [hadley/testthat#471]
when running a test from RStudio (Ctrl+Shift+T) with `with_mock` there is at least one function that cannot be mocked - `system.file`; this is because _devtools_ intercepts calls to this function

one possible way to handle this would be to change with_mock and detect whether `system.file` is being mocked while under _devtools_ - and in that case assign `system.file` in that function's environment

**Comment by krlmlr** [comment]
Have you tried to mock `devtools:::shim_system.file()` in addition to `system.file()`? An alternative is to explicitly add `system.file` to your package's environment in `.onLoad()`:

```
.onLoad <- function(libname, pkgname) {
  assign("system.file", base::system.file, envir = asNamespace(pkgname))
}
```

Not very elegant, but I doubt that `with_mock()` should be changed because of the behavior of another package.
