### ISSUE TITLE
testthat exit with status 1 when a test fails

### ISSUE THREAD

**Issue by Christoph999** [hadley/testthat#479]
I updated R to R-3.3.0 and updated afterwards testthat. Now I always get the following message when a(ny) test fails:

Fehler: testthat unit tests failed
Ausführung angehalten
Warnmeldung:
Ausführung von Kommando '"C:/R/R-33~1.0/bin/x64/Rterm.exe" --vanilla --slave -f "testthat.R"' ergab Status 1 
Tests complete

I checked that all tests were performed. Is there any reason for that (Unfortunately I get german error messages). To me, also the path ".../R-33~1.0/bin..." is odd.

Furthermore, is there a reason that no dots are displayed for each passed test?

Please let me know if you need a translation or anything else...

**Comment by krlmlr** [comment]
Which package are you testing? Are the tests wrapped in `test_that()`?

**Comment by Christoph999** [comment]
I tested my own package, the tests were contained in `testthat()` and they ran in the past "as expected". In the meanwhile, something changed: The error messages as described above together with the new testthat-summary are gone. I didn't change anything on the system side, so I can't imagine what happend.

**Comment by krlmlr** [comment]
I haven't found your package on GitHub. Could you please post a link, or a small example?

**Comment by Christoph999** [comment]
Sorry, it is a privat folder. I checked again: I cannot reproduce the error any more (although it was reproducible). I'd suggest to close the issue. If it occurs again, I will let you know. Thanks for your effort.
