### ISSUE TITLE
S3 methods in helpers

### ISSUE THREAD

**Issue by krlmlr** [hadley/testthat#480]
For some reason, it seems necessary to explicitly register S3 methods declared in helpers via registerS3method(). If this is not done, the tests find the S3 methods with devtools::test() but fail to find the S3 methods with R CMD check.

Example from tibble: https://github.com/hadley/tibble/pull/51/commits/c1e71be2febdab5b42a4943599ad55a413e4a921

Could #348 be related?

**Comment by hadley** [comment]
I'm going to say just don't do that — it is likely related to the environment not being on the search path.
