### ISSUE TITLE
Extract helpers for expect_equals?

### ISSUE THREAD

**Issue by hadley** [hadley/testthat#482]
i.e. `expect_attr_equal()`, `expect_element_equal()`, `expect_slot_equal()`.  

This would let you do quick equality tests in a pipe for subcomponents.  If you wanted to test for other things, you'd still need to manually extract

**Comment by hadley** [comment]
But this isn't particularly elegant because it requires special casing equality tests. You can almost already handle this problem with the tee pipe:

```R
library(testthat)
library(magrittr)

x <- list(
  a = 1,
  b = 2
)

x %>%
  expect_type("list") %T>%
  {expect_equal(.$a, 1)} %T>%
  {expect_equal(.$b, 2)}
```

But it's not particularly elegant.

Ideally, the tree structure of the testing code would reflect the tree structure of the object.

**Comment by hadley** [comment]
Or maybe:

```R
x %>%
  expect_type("list") %>%
  tee(.$a %>% expect_equal(1)) %>%
  tee(.$b %>% expect_equal(b)) %>%
```

**Comment by krlmlr** [comment]
This looks very similar to what `ensurer` already does.

**Comment by krlmlr** [comment]
Also, wouldn't we want to use something like

```
x %>%
  expect_type("list") %>%
  tee(
    expect_equal(.data$a, 1), 
    expect_equal(.data$b, 2)
  )
```

(and optionally omit `.data`)?

**Comment by hadley** [comment]
I don't think so - `tee()` is very simple to implement if we rely on the existing magrittr semantics.
