### ISSUE TITLE
Warnings are not handled correctly

### ISSUE THREAD

**Issue by robwe** [hadley/testthat#483]
Issue #254 is still not fixed in testthat 1.0.2.

Given the function under test, which generates a warning, because `asin(2)` is `NaN`:

    f = function() {
        options(warn = 2)
        result = NULL
        result = withCallingHandlers(
                expr = asin(2),
                error = function(error) { result <<- 42 }
        )
    }

then calling

            expect_identical(42, f())

works as expected, i.e. result is indeed 42. However, when you put the same code inside of test_that(), 

    test_that("withCallingHandlers handles warnings as errors, when warnings are converted to errors", {
            expect_identical(42, f())
        })

it fails, because result is `NaN`.

**Comment by krlmlr** [comment]
I'm seeing:

```
>  expect_identical(42, f())
Error in asin(2) : (converted from warning) NaNs produced
> test_that("withCallingHandlers handles warnings as errors, when warnings are converted to errors", {
+         expect_identical(42, f())
+     })
Error: Test failed: 'withCallingHandlers handles warnings as errors, when warnings are converted to errors'
* 42 not identical to f().
1/1 mismatches
[1] 42 - NaN == NaN
```

The behavior looks fairly reasonable to me, what would you like to change? I also don't see how this is related to #254.

**Comment by robwe** [comment]
The return value of function `f()` is `42`. However, when you call it inside of `test_that()`, then the return value is `NaN`. Hence `test_that()` changes the behaviour of the function under test. It must not do that. I expect the test to pass.
I suspect that this is caused by using `options(warn = 2)` and this is what issue #254 is about.

**Comment by krlmlr** [comment]
`f()` gives an error on my system, in `test_that()` it is reported as 42.

It's the behavior of the option that changes: the `warn` option is only interpreted in the [default warning handler](https://github.com/wch/r-source/blob/159691fa7529fc9ae6d9009faf84f9b8a1cf4464/src/main/errors.c#L348-L351), which is not reached when running in `testthat`.

I'd rather document this behavior. After all, the behavior of *ignoring* the `warn` option to have a controlled test scenario makes a lot of sense to me.

**Comment by robwe** [comment]
It is correct that `f()` converts the warning into an error and returns 42. However, in `test_that()` it does not do that and returns `NaN`.

Our team has the policy that productive, non-interactive R code should be written in such a way that no warnings occur. A warning means that something happened that the programmer had not foreseen and most likely will lead to wrong results downstream. We don't want this to go more or less unnoticed and hence we want all warnings to be treated as errors so that processing stops and the error handling takes over. For this we set `options(warn = 2)`.
If you decide to ignore this setting, then most of our negative testing (i.e. testing of warning scenarios) is not possible with `test_that()`.

**Comment by krlmlr** [comment]
Nobody likes warnings in production code. Therefore, modern testthat reports all warnings in the end, so you don't even need to set options(warn = 2).

```r
testthat::with_reporter(
  "summary",
  testthat::test_that("oops", warning("gotcha"))
)
```

Output:

```
W
Warnings -----------------------------------------------------------------------------------------------
1. oops - gotcha

DONE ===================================================================================================
```

Take a look at the FailReporter, I'm using it to make sure that the exit code of the R process that runs the tests is nonzero iff any test fails:

```bash
R -e 'devtools::testthat(reporter = c("summary", "fail"))'
```

You seem to need a FailOnWarningReporter, too, if you want the same behavior for warnings.

**Comment by hadley** [comment]
@robwe you need to describe why the current behaviour of testthat does not work for you. As @krlmlr described, warnings are _not_ silent.

**Comment by robwe** [comment]
As explained, in production code I want warnings to be treated as errors. This means that if there is a warning, execution of the code does NOT continue (as it normally would do for warnings) and the error handler of a `tryCatch` takes over. Therefore my production code contains the statement `options(warn=2)`. So far so good.
Additionally I would like to unit test my code using testthat.
In one of my tests I want to verify, that when a warning is generated, that indeed code execution stops and the error handling is done instead.
But: When my code runs inside of `test_that()`, then the `warn` option is ignored and instead of the stopping and error handling the code execution continues and leads to another result. Hence the test fails although I know that the code works correctly.
As a simplified version of my real code I have provided the function `f()`. If behaves differently when run outside of `test_that()` (return value is `42`) than when run inside of `test_that()`  (return value is `NaN`).
A test framework should not modify the behaviour of the function under test.
I think it is bad that I have to choose between using `options(warn=2)` in my code or using testthat. In an ideal world I could use `options(warn=2)` in my code and still it would behave the same inside and outside of `test_that()`.

**Comment by krlmlr** [comment]
@robwe: `f()` outside of `test_that()` still doesn't return 42 on my system, as I wrote much earlier:

```r
f = function() {
  result = NULL
  result = withCallingHandlers(
    expr = asin(2),
    error = function(error) { result <<- 42 }
  )
}

options(warn = 2)

f()
## Error in asin(2) : (converted from warning) NaNs produced
```

You'd need to catch a warning here, not an error. It would be great if you could adapt your example.

**Comment by robwe** [comment]
I made a mistake in my demo function `f()`. I edited my initial post and replace the `withCallingHandlers` with `tryCatch`. But everything else I said should remain true, i.e. outside of `test_that()` `f()` returns `42` and inside it returns `NaN`.
Sorry for the confusion.
