### ISSUE TITLE
warning() thrown in a tryCatch handler is not properly detected by expect_error()

### ISSUE THREAD

**Issue by wch** [hadley/testthat#484]
For example:

```R
f <- function() {
  tryCatch(
    stop("error here"),
    error = function(e) {
      warning(e)
    }
  )
}

expect_warning(f())
# Error: f() showed 0 warnings
# In addition: Warning message:
# In doTryCatch(return(expr), name, parentenv, handler) : error here
```

But if an `error()` is thrown in the error handler, `expect_error()` detects it:

```R
g <- function() {
  tryCatch(
    stop("error here"),
    error = function(e) {
      stop(e)
    }
  )
}

expect_error(g()) # OK
```

**Comment by wch** [comment]
Hm, this might be just a problem with my understanding of how R handles re-thrown exceptions. If I just extract the message from `e` and throw a warning with that, it works fine:

```R
f <- function() {
  tryCatch(
    stop("error here"),
    error = function(e) {
      warning(e$message)
    }
  )
}

expect_warning(f()) # OK
```

**Comment by krlmlr** [comment]
The handler installed by `testthat` seems to dispatch by the class indeed:

```r
tryCatch(warning(simpleError("oops")), error = function(e) "Hi")
# [1] "Hi"
```

I guess the problem here is that warning() and error() don't check/patch the class of the condition object. It's somewhat documented that "warning (effectively) calls signalCondition".
