### ISSUE TITLE
expect_equivalent() gives misleading error message

### ISSUE THREAD

**Issue by dlindelof** [hadley/testthat#485]
When comparing two objects that are numerically different and have different names, I expect `expect_equivalent()` to complain about the numeric differences and ignore the names. Instead it reports a difference in the names:

```
> expect_equivalent(c(foo = 0), 1)
Error: c(foo = 0) not equivalent to 1.
names for target but not for current
> expect_equivalent(c(foo = 0), 0)
```

**Comment by krlmlr** [comment]
Works as expected for character values already:

```
> expect_equivalent(c(foo = "0"), "1")
Error: c(foo = "0") not equivalent to "1".
1/1 mismatches
x[1]: "0"
y[1]: "1"
```
