### ISSUE TITLE
with_mock() seems to fail in R CMD check with unqualified functions

### ISSUE THREAD

**Issue by krlmlr** [hadley/testthat#488]
Need to write

``` r
with_mock(
  `package::fun` = function() ...
)
```

instead of 

``` r
with_mock(
  fun = function() ...
)
```

if `fun()` is a function in the tested package, because the latter doesn't seem to work in R CMD check.

krlmlr/dplyr@8a166c32b7a3d8485e

**Comment by hadley** [comment]
I'm going to close this because I don't think we want to do any more work on mocking in testthat, instead relying on add on packages.
