### ISSUE TITLE
Think about lazy evaluation

### ISSUE THREAD

**Issue by krlmlr** [hadley/testthat#489]
```
expect_true_( ~some_function( .(arg1), arg2 ) )
```

would show `Not true: some_function( <value of arg1>, arg2 )` in case of a failure. Needs to generalize for all expectations, perhaps the necessary forwarders (`expect_true_()` -> `expect_true()`) could be metaprogrammed.

**Comment by hadley** [comment]
This would give referential integrity for tests because 

```R
expect_warning(foo())
```

is not equivalent to

```R
bar <- foo()
expect_warning(bar)
```

It would also be useful for tests that don't use special evaluation because you'd get quasiquotation which gives better messages when called in a loop.

**Comment by krlmlr** [comment]
I don't understand "referential integrity", but I think I get the idea. Quasiquotation would be very useful for DBItest.

Perhaps the forwarding should go the other way round, though: `expect_true()` -> `expect_true_()`.

**Comment by hadley** [comment]
Superseded by #626
