### ISSUE TITLE
Implement better menu()

### ISSUE THREAD

**Issue by krlmlr** [hadley/testthat#500]
The current menu() relentlessly shows all entries, even if it's thousands: https://github.com/hadley/testthat/pull/470/files#diff-4b2b05efa7c3220aca6e3c0281332791R17. A better menu() would show the first and last 10 entries first, with a ... inbetween, just like the first_last() function does. Selecting the ... would show the first and last 20 entries, etc.

**Comment by hadley** [comment]
Is menu used anywhere in testthat, or just in that mocking test?

**Comment by krlmlr** [comment]
It's used in our copy of recover(), so this change would also allow mocking (#553). I'll take a look.

@gaborcsardi: Do you know/have a fancy alternative for `utils::menu()`?

**Comment by gaborcsardi** [comment]
@krlmlr What I have is experimental, so, sorry, not currently.

**Comment by hadley** [comment]
This seems sufficiently low priority that I'm going to close it.
