### ISSUE TITLE
Piping to and from output expectations

### ISSUE THREAD

**Issue by fangly** [hadley/testthat#508]
Hi there,

I am wondering how the pipe symbol %>% is supposed to behave with output expectations. Note that piping is entirely omitted from the PDF documentation of testthat version 1.0.2 . Hence, the only thing I know about piping is what I read on https://blog.rstudio.org/2016/04/29/testthat-1-0-0/ .

*\* Use case of output expectation piping**
I would have liked to write something like this:

```
sqrt(4) %>% expect_error(NA) %>% expect_equal(2.0)
```

Obviously, if sqrt() generated an error, it would not make sense to then call expect_equal(). However, here, I expect no error and would like to pipe to test additional things.

**Piping in problem**
A potential problem is that using the piping syntax, sqrt() is evaluated fist, and then passed to expect_error(). Thus, we loose the capability of expect_error() to run tryCatch() to capture any error message like it is done when issuing expect_error(sqrt(4),NA) directly.

**Piping out problem**
invisible(NULL) is returned from expect_error(), expect_warning() and expect_message(), which prevents them from piping to other downstream expectations. One should perhaps consider returning something better to allow piping out. At the very least, I suggest mentionning in the documentation that these expectations cannot pipe to other expectations.

Cheers!

Florent

**Comment by hadley** [comment]
I think it's just best to not using piping with error/message/warning expectations (because, as you note, the code is executed prior to piping), which is why they use `NULL`
