### ISSUE TITLE
Use capture_output_as_vector()

### ISSUE THREAD

**Issue by krlmlr** [hadley/testthat#509]
The pattern is used in the same module, the existing function can be reused.

**Comment by hadley** [comment]
Can you provide a little more context? (Or a PR?)

**Comment by krlmlr** [comment]
I think this was about replacing the capture.output() calls with capture_output_as_vector() for consistency.

**Comment by hadley** [comment]
Ok. I'll probably also rename to `capture_output` for the sake of brevity

**Comment by krlmlr** [comment]
capture_output() captures as a single string and is exported already.

**Comment by hadley** [comment]
Oooh, bummer. `capture_outputs()` ?

**Comment by krlmlr** [comment]
`capture_output_lines()` sounds better.

**Comment by hadley** [comment]
We don't seem to use `capture.output` any more
