### ISSUE TITLE
Fix expect_output_file() on Windows

### ISSUE THREAD

**Issue by krlmlr** [hadley/testthat#510]
Need to read and write as UTF-8 with LF (krlmlr/utf8#8).

**Comment by hadley** [comment]
Is there any easy fix for this?

**Comment by krlmlr** [comment]
By now we have `read_lines_with_encoding()` in this package. We also need a better writing function w.r.t. encoding and line separator. I wonder if the utf8 package is a better place for these functions; I might be able to release utf8 just in time.
