### ISSUE TITLE
segfault installing testthat 1.0.2 on R.3.2.2 using tar.gz file dowloaded from CRAN

### ISSUE THREAD

**Issue by george-weingart** [hadley/testthat#511]
Hello,
I am getting a segfault installing testthat 1.0.2: 
Details:  Downloaded the tar.gz file from CRAN at 
https://cran.r-project.org/src/contrib/testthat_1.0.2.tar.gz 
When I go to R (3.2.2) and enter the command: 
install.packages('testthat_1.0.2.tar.gz') 
I get the following error:

> install.packages('testthat_1.0.2.tar.gz')
> Installing package into ‘/n/home09/george.weingart/R/x86_64-redhat-linux-gnu-library/3.2’
> (as ‘lib’ is unspecified)
> inferring 'repos = NULL' from 'pkgs'
> - installing _source_ package ‘testthat’ ...
>   *\* package ‘testthat’ successfully unpacked and MD5 sums checked
>   *\* libs
>   gcc -m64 -std=gnu99 -I/usr/include/R    -I../inst/include -DCOMPILING_TESTTHAT -I/usr/local/include    -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic  -c label.c -o label.o
>   gcc -m64 -std=gnu99 -I/usr/include/R    -I../inst/include -DCOMPILING_TESTTHAT -I/usr/local/include    -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic  -c reassign.c -o reassign.o
>   g++ -m64 -I/usr/include/R    -I../inst/include -DCOMPILING_TESTTHAT -I/usr/local/include    -fpic  -O3 -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic    -c test-catch.cpp -o test-catch.o
>   g++ -m64 -I/usr/include/R    -I../inst/include -DCOMPILING_TESTTHAT -I/usr/local/include    -fpic  -O3 -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic    -c test-example.cpp -o test-example.o
>   g++ -m64 -I/usr/include/R    -I../inst/include -DCOMPILING_TESTTHAT -I/usr/local/include    -fpic  -O3 -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic    -c test-runner.cpp -o test-runner.o
>   g++ -m64 -shared -L/usr/lib64/R/lib -L/usr/local/lib64 -o testthat.so label.o reassign.o test-catch.o test-example.o test-runner.o -L/usr/lib64/R/lib -lR
>   installing to /n/home09/george.weingart/R/x86_64-redhat-linux-gnu-library/3.2/testthat/libs
>   *\* R
>   *\* inst
>   *\* preparing package for lazy loading

 **\* caught segfault ***
address 0x5, cause 'memory not mapped'

Traceback:
 1: .Call("digest", object, as.integer(algoint), as.integer(length),     as.integer(skip), as.integer(raw), PACKAGE = "digest")
 2: `_digest`(c(list(), lapply(`_additional`, function(x) eval(x[[2L]],     environment(x)))), algo = "sha512")
 3: i_num_colors()
 4: num_colors(forget = TRUE)
 5: fun(libname, pkgname)
 6: doTryCatch(return(expr), name, parentenv, handler)
 7: tryCatchOne(expr, names, parentenv, handlers[[1L]])
 8: tryCatchList(expr, classes, parentenv, handlers)
 9: tryCatch(fun(libname, pkgname), error = identity)
10: runHook(".onLoad", env, package.lib, package)
11: loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]])
12: asNamespace(ns)
13: namespaceImportFrom(ns, loadNamespace(j <- i[[1L]], c(lib.loc,     .libPaths()), versionCheck = vI[[j]]), i[[2L]], from = package)
14: loadNamespace(package, lib.loc, keep.source, partial = TRUE)
15: withCallingHandlers(expr, packageStartupMessage = function(c) invokeRestart("muffleMessage"))
16: suppressPackageStartupMessages(loadNamespace(package, lib.loc,     keep.source, partial = TRUE))
17: code2LazyLoadDB(package, lib.loc = lib.loc, keep.source = keep.source,     compress = compress)
18: makeLazyLoading(pkg_name, lib, keep.source = keep.source)
19: doTryCatch(return(expr), name, parentenv, handler)
20: tryCatchOne(expr, names, parentenv, handlers[[1L]])
21: tryCatchList(expr, classes, parentenv, handlers)
22: tryCatch(expr, error = function(e) {    call <- conditionCall(e)    if (!is.null(call)) {        if (identical(call[[1L]], quote(doTryCatch)))             call <- sys.call(-4L)        dcall <- deparse(call)[1L]        prefix <- paste("Error in", dcall, ": ")        LONG <- 75L        msg <- conditionMessage(e)        sm <- strsplit(msg, "\n")[[1L]]        w <- 14L + nchar(dcall, type = "w") + nchar(sm[1L], type = "w")        if (is.na(w))             w <- 14L + nchar(dcall, type = "b") + nchar(sm[1L],                 type = "b")        if (w > LONG)             prefix <- paste0(prefix, "\n  ")    }    else prefix <- "Error : "    msg <- paste0(prefix, conditionMessage(e), "\n")    .Internal(seterrmessage(msg[1L]))    if (!silent && identical(getOption("show.error.messages"),         TRUE)) {        cat(msg, file = stderr())        .Internal(printDeferredWarnings())    }    invisible(structure(msg, class = "try-error", condition = e))})
23: try({    suppressPackageStartupMessages(.getRequiredPackages(quietly = TRUE))    makeLazyLoading(pkg_name, lib, keep.source = keep.source)})
24: do_install_source(pkg_name, instdir, pkg, desc)
25: do_install(pkg)
26: tools:::.install_packages()
aborting ...
/usr/lib64/R/bin/INSTALL: line 34: 43961 Done                    echo 'tools:::.install_packages()'
     43962 Segmentation fault      (core dumped) | R_DEFAULT_PACKAGES= LC_COLLATE=C "${R_HOME}/bin/R" $myArgs --slave --args ${args}
Warning message:
In install.packages("testthat_1.0.2.tar.gz") :
  installation of package ‘testthat_1.0.2.tar.gz’ had non-zero exit status

**Comment by kevinushey** [comment]
Try reinstalling `digest` and trying again.

```
install.packages("digest")
```

**Comment by george-weingart** [comment]
Hi Kevin,
First of all, thanks for your prompt response !
Got an error after installing digest.
Thanks!
George

> packageVersion('digest')
[1] ‘0.6.9’
> install.packages('testthat_1.0.2.tar.gz')
Installing package into ‘/n/home09/george.weingart/R/x86_64-redhat-linux-gnu-library/3.2’
(as ‘lib’ is unspecified)
inferring 'repos = NULL' from 'pkgs'
* installing *source* package ‘testthat’ ...
** package ‘testthat’ successfully unpacked and MD5 sums checked
** libs
gcc -m64 -std=gnu99 -I/usr/include/R    -I../inst/include -DCOMPILING_TESTTHAT -I/usr/local/include    -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic  -c label.c -o label.o
gcc -m64 -std=gnu99 -I/usr/include/R    -I../inst/include -DCOMPILING_TESTTHAT -I/usr/local/include    -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic  -c reassign.c -o reassign.o
g++ -m64 -I/usr/include/R    -I../inst/include -DCOMPILING_TESTTHAT -I/usr/local/include    -fpic  -O3 -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic    -c test-catch.cpp -o test-catch.o
g++ -m64 -I/usr/include/R    -I../inst/include -DCOMPILING_TESTTHAT -I/usr/local/include    -fpic  -O3 -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic    -c test-example.cpp -o test-example.o
g++ -m64 -I/usr/include/R    -I../inst/include -DCOMPILING_TESTTHAT -I/usr/local/include    -fpic  -O3 -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic    -c test-runner.cpp -o test-runner.o
g++ -m64 -shared -L/usr/lib64/R/lib -L/usr/local/lib64 -o testthat.so label.o reassign.o test-catch.o test-example.o test-runner.o -L/usr/lib64/R/lib -lR
installing to /n/home09/george.weingart/R/x86_64-redhat-linux-gnu-library/3.2/testthat/libs
** R
** inst
** preparing package for lazy loading

 *** caught segfault ***
address 0x5, cause 'memory not mapped'

Traceback:
 1: .Call("digest", object, as.integer(algoint), as.integer(length),     as.integer(skip), as.integer(raw), PACKAGE = "digest")
 2: `_digest`(c(list(), lapply(`_additional`, function(x) eval(x[[2L]],     environment(x)))), algo = "sha512")
 3: i_num_colors()
 4: num_colors(forget = TRUE)
 5: fun(libname, pkgname)
 6: doTryCatch(return(expr), name, parentenv, handler)
 7: tryCatchOne(expr, names, parentenv, handlers[[1L]])
 8: tryCatchList(expr, classes, parentenv, handlers)
 9: tryCatch(fun(libname, pkgname), error = identity)
10: runHook(".onLoad", env, package.lib, package)
11: loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]])
12: asNamespace(ns)
13: namespaceImportFrom(ns, loadNamespace(j <- i[[1L]], c(lib.loc,     .libPaths()), versionCheck = vI[[j]]), i[[2L]], from = package)
14: loadNamespace(package, lib.loc, keep.source, partial = TRUE)
15: withCallingHandlers(expr, packageStartupMessage = function(c) invokeRestart("muffleMessage"))
16: suppressPackageStartupMessages(loadNamespace(package, lib.loc,     keep.source, partial = TRUE))
17: code2LazyLoadDB(package, lib.loc = lib.loc, keep.source = keep.source,     compress = compress)
18: makeLazyLoading(pkg_name, lib, keep.source = keep.source)
19: doTryCatch(return(expr), name, parentenv, handler)
20: tryCatchOne(expr, names, parentenv, handlers[[1L]])
21: tryCatchList(expr, classes, parentenv, handlers)
22: tryCatch(expr, error = function(e) {    call <- conditionCall(e)    if (!is.null(call)) {        if (identical(call[[1L]], quote(doTryCatch)))             call <- sys.call(-4L)        dcall <- deparse(call)[1L]        prefix <- paste("Error in", dcall, ": ")        LONG <- 75L        msg <- conditionMessage(e)        sm <- strsplit(msg, "\n")[[1L]]        w <- 14L + nchar(dcall, type = "w") + nchar(sm[1L], type = "w")        if (is.na(w))             w <- 14L + nchar(dcall, type = "b") + nchar(sm[1L],                 type = "b")        if (w > LONG)             prefix <- paste0(prefix, "\n  ")    }    else prefix <- "Error : "    msg <- paste0(prefix, conditionMessage(e), "\n")    .Internal(seterrmessage(msg[1L]))    if (!silent && identical(getOption("show.error.messages"),         TRUE)) {        cat(msg, file = stderr())        .Internal(printDeferredWarnings())    }    invisible(structure(msg, class = "try-error", condition = e))})
23: try({    suppressPackageStartupMessages(.getRequiredPackages(quietly = TRUE))    makeLazyLoading(pkg_name, lib, keep.source = keep.source)})
24: do_install_source(pkg_name, instdir, pkg, desc)
25: do_install(pkg)
26: tools:::.install_packages()
aborting ...
/usr/lib64/R/bin/INSTALL: line 34: 46029 Done                    echo 'tools:::.install_packages()'
     46030 Segmentation fault      (core dumped) | R_DEFAULT_PACKAGES= LC_COLLATE=C "${R_HOME}/bin/R" $myArgs --slave --args ${args}
Warning message:
In install.packages("testthat_1.0.2.tar.gz") :
  installation of package ‘testthat_1.0.2.tar.gz’ had non-zero exit status
