### ISSUE TITLE
test_check honors filter; devtools::test does not

### ISSUE THREAD

**Issue by dmenne** [hadley/testthat#516]
In the attached minimal example package, when I run `test_check` explicitly, the filter settings are honored and the attached package passes.

When I run `devtools::test` or use "Test package" in Rstudio, filter settings are ignored and the package tests fail.

[testthatfilter.zip](https://github.com/hadley/testthat/files/426504/testthatfilter.zip)

Tested under Windows 10, R version 3.3.1 (2016-06-21), testthat 1.0.2

**Comment by hadley** [comment]
What do you mean by "filter settings"?

**Comment by dmenne** [comment]
`test_check("testthatfilter", filter = "pass")`

**Comment by hadley** [comment]
Yes, that's the expected behaviour. `test()` always tests the complete package.
