### ISSUE TITLE
`print` option for `expect_output_file`

### ISSUE THREAD

**Issue by nabilabd** [hadley/testthat#517]
Hi, 

First, thanks for all the great work on this package. 

In trying to use the `expect_output_file` function, I'm getting an error. Here's an example: 

``` r
library(testthat)
tmp_fl <- tempfile(fileext = ".csv")
write.csv(mtcars, tmp_fl)
expect_output_file(mtcars, tmp_fl)
```

The problem seems to be that `testthat:::capture_output_as_vector` takes a `print` argument, which doesn't have a default defined in `expect_output_file`, whereas there is a default for when it is called in e.g., `testthat::capture_output`. From the documentation, I'm not quite sure what the `print` option would do, so I can't make the fix myself.

**Comment by dchiu911** [comment]
I have a similar issue to report regarding `expect_output`. One might expect both of the following calls to return output, but the second one doesn't:

```{r}
library(testthat)
expect_output(str(3), "3")
expect_output(sum(3, 4), "3")
# Error: sum(3, 4) produced no output
```
However, we see that `capture_output` captures something for both, when we use `print = TRUE`.
```{r}
capture_output(str(3), print = TRUE)
# [1] " num 3"
capture_output(sum(3, 4), print = TRUE)
# [1] "[1] 7"
```
It seems that `str()` calls are captured regardless of the `print` argument, which by default is `FALSE` inside `expect_output`. I am not sure why this is, but it may have something to do with:
```{r}
withVisible(str(3))
# num 3
# $value
# NULL
# 
# $visible
# [1] FALSE
withVisible(sum(3, 4))
# $value
# [1] 7
# 
# $visible
# [1] TRUE
```
Am I using `expect_output` correctly for its intended purpose?

**Comment by hadley** [comment]
@dchiu911 your question isn't related to this issue so I've deleted it. Please ask on a mailing list (e.g. rdevtools) or stackoverflow.
