### ISSUE TITLE
Option to stop tests earlier if more than n fail

### ISSUE THREAD

**Issue by hadley** [hadley/testthat#520]
Because it typically indicates something is seriously wrong, and you just want to see the errors right away.

**Comment by hadley** [comment]
@krlmlr how do you feel about this being the default behaviour? i.e. if there are `> getOption("testthat.summary.max_reports", 15L)` we terminate reporter early?

**Comment by krlmlr** [comment]
Now included in #502.

**Comment by hadley** [comment]
This is mildly tricky as we need a new subclass of stop that will immediately terminate execution of the entire test suite, and not get captured like usual errors.

**Comment by krlmlr** [comment]
Could you please check if https://github.com/hadley/testthat/pull/502/commits/de82b5be06b00934f56b77ccd9946c4d55eeb5b8 would also work?

**Comment by hadley** [comment]
I wrote my comment on the plane a couple of days ago when I didn't have internet access and only just submitted it. I think your approach is fine.

**Comment by hadley** [comment]
Open browser tab ;)
