### ISSUE TITLE
How to test own expectation for failure

### ISSUE THREAD

**Issue by schoettl** [hadley/testthat#525]
Hi, I could not find a solution so far for this:

I have written an own expectation, e.g. `is_symmetric`.

I test it like this:

```
a = matrix(c(1, 1, 1, 1), nrow=2)
expect_that(a, is_symmetric())
```

How can I test failure, i.e. the cases where my expectation is supposed to fail?

I tried these, but they do not work:

```
a = matrix(1:4, nrow=2)
expect_fail(expect_that(a, is_symmetric()))
```

```
a = matrix(1:4, nrow=2)
expect_that(is_symmetric()(a), throws_error())
```

**Comment by hadley** [comment]
At this point, you'll need to read the source for an expectation (e.g. https://github.com/hadley/testthat/blob/master/R/expect-length.R) and then read the source code for how it's tested in testthat (e.g. https://github.com/hadley/testthat/blob/master/tests/testthat/test-expect-length.R)

**Comment by schoettl** [comment]
Thank you! So the answer is `expect_failure(...)`. I already was pretty close with `expect_fail` ^^
