### ISSUE TITLE
Option to print out the contents in dataframes when they are different in expect_* APIs

### ISSUE THREAD

**Issue by HyukjinKwon** [hadley/testthat#526]
I took a look for the documentation, https://cran.r-project.org/web/packages/testthat/testthat.pdf and looked though StackOverFlow.

It seems there is no way to directly print out the dataframes when it fails to the comparison.

For example,

``` r
df <- data.frame(matrix(rnorm(10), nrow=5))
df1 <- data.frame(matrix(rnorm(10), nrow=5))
expect_equal(df, df1)
```

prints only some information about differences

``` r
Error: `df` not equal to `df1`.
Component “X1”: Mean relative difference: 1.281164
Component “X2”: Mean relative difference: 0.987835
```

It sometimes makes the debugging hard when the names are different as below:

``` r
> df <- data.frame(a=c(1,1,1),b=c(2,2,2))
> df1 <- data.frame(b=c(1,1,1),b=c(2,2,2))
> expect_equal(df, df1)
```

prints

``` r
Error: `df` not equal to `df1`.
Names: 2 string mismatches
```

I tried `info` option but it seems printing the info whether the test is failed or not.

I'd be great if it prints the dataframes maybe with an option. For example as below:

```
== Results ==
!== Expected Answer - 7 ==   == Actual Answer - 3 ==
 [1,0]                      [1,0]
![1,0]                      [2,0]
![1,0]                      [3,0]
![2,0]                    
![2,0]                    
![3,0]                    
![3,0] 
```

Otherwise, maybe, it'd be nicer if it just prints the dataframe contents at least.

Are they already concerned? Please let me know if there is any way to do this.

**Comment by hadley** [comment]
Succinctly describing the difference between two data frames is quite different, so is currently outside the scope of testthat. If there was a package that did it, I'd consider including in testthat.

**Comment by HyukjinKwon** [comment]
Thank you for your response.

**Comment by gaborcsardi** [comment]
@hadley How about https://github.com/brodieG/diffobj#readme ?

**Comment by hadley** [comment]
That looks good but we'd need to wait on ansi escape support in RStudio

**Comment by gaborcsardi** [comment]
@hadley it uses the viewer pane in RStudio. See the bottom of the screenshot.

I am not sure if you would always want this (i.e. seeing the differences in the viewer), but I am pretty sure that you do want it quite often, at least I would when checking why my expected output does not match the actual....

**Comment by hadley** [comment]
Yeah but that's not going to work with the usual way of running tests either.
