### ISSUE TITLE
Nice looking detailed reporter

### ISSUE THREAD

**Issue by gaborcsardi** [hadley/testthat#529]
AFAICT there is no such reporter currently. And I agree that you don't want to see this much output, usually, but e.g. personally I would be happy with more details on the CI. I will only look at the output when there is an issue, anyway, and then it would be great to see the problem immediately.

Something like this:

```
# mypackage

## context1 ────────────────────────────────────────────────

✔ [4/4] first_test
✔ [5/5] second_test
✖ [1/2] third_test
Error: "foo" not equal to 1.
Types not compatible: character vs double

## context2

...

## Summary

── 34 passed ✔ | 1 failed ✖ | 1 error ✖ | 1 warning ✖ ─────
```

**Comment by gaborcsardi** [comment]
Here is an even better looking example for motivation: https://raw.githubusercontent.com/DevExpress/testcafe/master/docs/articles/images/spec-report.png

**Comment by hadley** [comment]
Looks great. I'd love to review a PR :)

**Comment by gaborcsardi** [comment]
Haha. I actually already started writing it last week, in another package. It is unfortunately impossible to implement reporters in other packages, because I need to call `testthat` internals. What do you think about that? Should `testthat` provide a better API for reporter writers, or you would like to keep reporters in `testthat`?

As for this particular reporter, I think it can be in testthat, or separate, I really don't mind. It'll have some additional dependencies, but all lightweight, e.g. my `prettycode` package to syntax highlight the code, and/or `tracer` for nicer stack traces. 

I am also looking at https://github.com/brodieG/diffobj#readme to provide better looking reports about object differences.

Anyway, I don't think this will be ready for the next `testthat` release...

**Comment by hadley** [comment]
Let me know what you need exported and I can do it. I'd rather have new reporters in other packages so I'm not the bottleneck.

**Comment by hadley** [comment]
Concrete idea after iterating in slack:

```
  OK | F | E | W | S | Context 
x 20 |   |   |   |   | compare.character 
x 12 | 1 |   |   |   | compare.numeric 
-----------------------------------------------------------
Failure @test-compare-numeric.R#6: numeric types are compatible
compare(1, 2L)$equal isn't true.
-----------------------------------------------------------
/  5 |   |   |   |   | compare.time
```

* Status/spinner on left
* Just show counts (updating as the expectations complete)
* Show errors after each context
