### ISSUE TITLE
expect_error could handle the error class

### ISSUE THREAD

**Issue by gaborcsardi** [hadley/testthat#530]
I mean, I want to specify that I expect a given error class, instead of specifying the error message. AFAICT this is currently not possible.

**Comment by hadley** [comment]
Great idea. I'd be happy to review a PR :)

**Comment by hadley** [comment]
And presumably this should also cover warnings and messages. I'll have a go at it.

**Comment by hadley** [comment]
Oh `messages()` and `warnings()` are bit trickier because there might be more than one. I'll leave those for now.

**Comment by gaborcsardi** [comment]
Great! Thanks! This will allow proper error testing once we have proper error objects in R packages. :)
