### ISSUE TITLE
expect unique

### ISSUE THREAD

**Issue by rgknight** [hadley/testthat#533]
What do you think of an expect-unique that expects that `sum(duplicated(x))` is zero? 

It's straightforward to `expect_equal(sum(duplicated(x)), 0)`, but it seems like testing that code isn't introducing duplicates and retains the expected unique identifiers is fundamental test.

**Comment by hadley** [comment]
This feels a bit specialised to me — you can currently do `expect_false(anyDuplicated(x))`
