### ISSUE TITLE
Idea: use source markers in RStudio

### ISSUE THREAD

**Issue by gaborcsardi** [hadley/testthat#537]
To jump to the test failure quickly.

**Comment by hadley** [comment]
What's a source marker?  Can you provide a bit more context?

**Comment by hadley** [comment]
I think using `rstudioapi::sourceMarkers()` will be challenging because you really want to generate them them from `devtools::test()`, but that's called from an external session.

@kevinushey any ideas?

**Comment by gaborcsardi** [comment]
Yeah, just an idea. I don't use RStudio much, but when I do :), and I run `lintr` and `covr` I find it nice that I can just jump to the right place in the code with a click in the markers window.

Another solution, that I use in the terminal is to make source positions clickable in RStudio. The testthat output would need some changes for this as well. 

E.g. here is a screenshot. I could not include the mouse cursor, but imagine that it is above the `R/run.R:24:19` text. If I CMD+click on that, it brings up the file at sets the cursor at the given position.

<img width="1002" alt="screen shot 2016-12-15 at 9 57 53 am" src="https://cloud.githubusercontent.com/assets/660288/21219531/1481f6c0-c2ad-11e6-8ba6-ed7bb0a5ceff.png">

If RStudio runs testthat in another session, then yes, you would need a way to get the results back, and probably the best way is to have a specific RStudio reporter. But I understand that this is sg that you need to implement in RStudio (as well).

**Comment by kevinushey** [comment]
Because tests are indeed run in a separate R session I don't think the work necessary here could happen (at least in a straight-forward way) with code in `testthat`. There are plans to enable Ctrl + Click navigation to errors directly from the Build pane in RStudio, though.

**Comment by gaborcsardi** [comment]
:+1:
