### ISSUE TITLE
Idea: a way of listing all possible reporters

### ISSUE THREAD

**Issue by micstr** [hadley/testthat#539]
Please could there be better documentation on what reporters are available. 

Currently I dig around in the index file to discover reporter styles like "TapReporter" or "ListReporter", beyond the summary one. 

I see there is a Rstudio one being worked on as well. Currently the only documentation being referenced is the testing chapter ("Instructions for using this package can be found in the Testing chapter of R packages.") which does not cover reporters.

Please could there be a function "DescribeReporters" or mini vignette that lists all the reporters and their differences? Thanks so much.

**Comment by hadley** [comment]
At this point your best option is just to look at the overall documentation: `help(package = "testthat")`.   

I'll add a `@family` tag so that they're cross-referenced in the next version
