### ISSUE TITLE
[Request] assert_that function that's appropriate for use within a function

### ISSUE THREAD

**Issue by kendonB** [hadley/testthat#541]
Currently, if I try to use ``expect*`` within functions I get funny behavior with ``expect_error`` when trying to violate the expectation in the function:

```
square_root <- function(x){
  testthat::expect_gte(x, 0)
  sqrt(x)
}

expect_error(square_root(-1))
# Error: -1 is not more than 0. Difference: -1 

square_root <- function(x){
  stopifnot(x >= 0)
  sqrt(x)
}

expect_error(square_root(-1))
# works
```

``assertthat`` works as well, but development on that package seems to have stalled. Is it possible to add an ``assert_that`` function to ``testthat`` that would work like this:

```
square_root <- function(x){
  testthat::assert_that("x input is positive", {
    expect_gte(x, 0)
  })
  sqrt(x)
}

expect_error(square_root(-1))
# would work
```
``assert_that`` would somehow make the error behavior from ``expect*`` functions work like ``stopifnot``.

**Comment by gaborcsardi** [comment]
I think `assertthat` is fine. Yes, not developed too actively, but it is also "complete".

**Comment by kendonB** [comment]
The msg argument in assertthat makes that package worth using for me (over stopifnot). But that feature isn't on the cran version (hence my comment about development, see https://github.com/hadley/assertthat/issues/36). This is fine for me, but I work with and share code with people who don't know what github is.

The advantage  of having in-function assertions here would be to prevent duplication of the numerous expect* functions and associated error messages. It just seems tidier.

Hope this helps!

**Comment by gaborcsardi** [comment]
You can define nice error messages with the CRAN version, e.g.

```r
is_string <- function(x) {
  is.character(x) && length(x) == 1 && !is.na(x)
}

on_failure(is_string) <- function(call, env) {
  paste0(sQuote(deparse(call$x)), " is not a string (length 1 character)")
}
```

**Comment by kendonB** [comment]
Thanks for the reply! I think this is a nice (though not nearly as user-friendly as ``msg``) solution for defining new ``is_*`` assertion functions, but 99% of my use cases are assertions on situations I've never seen before (see a real example below with variable names changed). Using ``if + stop`` with a custom message is my best solution at the moment, and a lot tidier than defining a new assertion function every time with ``on_failure...paste0(sQuote(deparse(call$x))``.

Another advantage of testthat over assertthat is it runs tests in new environments, so the extra objects created during an assertion wouldn't accidentally get used later in the function.

Thanks again!
```
assert_that({
  df_2 <- df %>% 
    group_by(var1, var2, var3, var4, var5) %>% 
    filter(n() > 1)
  
  df_3 <- df %>% 
    group_by(var1, var2, var3, var4, var5) %>% 
    filter(n() > 1,  length(unique(var6)) == n())
  NROW(df_2) == NROW(df_3)
  }, msg = paste0("There are apparent duplicates in the data (var4 with more than one var1-var5",
                  "These appear to be all  OTHER (COMBINED) var4s over multiple var6s.",
                  "If you see this message, then there are also duplicate var6s somewhere."))
```

**Comment by hadley** [comment]
This seems like it's out of scope currently.
