### ISSUE TITLE
with_mock interacts badly with the JIT

### ISSUE THREAD

**Issue by gaborcsardi** [hadley/testthat#543]
Because the JIT itself is R code, and the mocking will be active for the JIT, potentially breaking it.

**Comment by krlmlr** [comment]
Do you have an example?

**Comment by gaborcsardi** [comment]
https://github.com/gaborcsardi/debugme/blob/ed7f9aad291954a96f5d7aa3cc1981de8ed2b095/tests/testthat/test-package.R#L18-L37

The JIT uses `match`...

**Comment by gaborcsardi** [comment]
OK, so in the light of #546 I can close this.

**Comment by krlmlr** [comment]
Just for completeness: How do I trigger the faulty behavior here? I tried in R-devel:

```
R -e 'compiler::enableJIT(TRUE); devtools::test()'
```

but the tests still passed.

**Comment by gaborcsardi** [comment]
I don't know, TBH. Maybe @kalibera does.

**Comment by kalibera** [comment]
You can trigger this e.g. when pre-compiling testthat
`env R_COMPILE_PKGS=1 ./bin/R CMD check down/testthat_1.0.2.tar.gz`

**Comment by krlmlr** [comment]
Thanks, Tomas. After

```
R_COMPILE_PKGS=1 R CMD check testthat_1.0.2.9000.tar.gz
```

with R-devel I'm getting a failed example:

```
Running examples in ‘testthat-Ex.R’ failed
The error most likely occurred in:

> ### Name: with_mock
> ### Title: Mock functions in a package.
> ### Aliases: with_mock
> 
> ### ** Examples
> 
> with_mock(
+   all.equal = function(x, y, ...) TRUE,
+   expect_equal(2 * 3, 4),
+   .env = "base"
+ )
[1] 6
> with_mock(
+   `base::identical` = function(x, y, ...) TRUE,
+   `base::all.equal` = function(x, y, ...) TRUE,
+   expect_equal(x <- 3 * 3, 6),
+   expect_identical(x + 4, 9)
+ )
Error: x + 4 not identical to 9.
Objects equal but not identical
Execution halted
```

Is this what you're seeing too?

**Comment by kalibera** [comment]
Yes. I did not debug this case any further - as Hadley wants to get rid of the mocking anyway. So I don't know exactly why this example fails. In general, you cannot safely modify functions in base namespace. It can confuse the JIT (which is R code, like in case of debugme package tests), it can confuse other R code running asynchronously (e.g. finalizers). This is why bindings are locked in namespaces and should stay locked (in any namespace, not only in base).
