### ISSUE TITLE
Cases with external references

### ISSUE THREAD

**Issue by lionel-** [hadley/testthat#548]
See if the `cases` management can be extracted from vdiffr and used in testthat (for `expect_equal_to_reference()` and `expect_output_file()`.

**Comment by hadley** [comment]
Can you provide any more details here? (i.e. a link to the relevant vdiffr code)

**Comment by lionel-** [comment]
It's probably about management of comparison files. For instance there should be some garbage collection procedure for reference files whose expectation has been removed from unit tests.

I don't think the current vdiffr implementation is the right fit for testthat though. It currently works like this:

- If the reference expectation (in vdiffr case `expect_doppelganger()`) is run in a normal test session, the test case generated by the expectation is compared to the reference file if it exists. See https://github.com/lionel-/vdiffr/blob/master/R/testthat-ui.R

- If the reference expectation is run in a "collecting" session, the cases are collected. They can be either a `success`, a `failure`, a `new` case (the reference file doesn't exist yet), or an `orphan`. There is a procedure to remove the reference files of orphans. See https://github.com/lionel-/vdiffr/blob/master/R/cases.R

Ideally the cases should be collected in normal testing sessions which is why vdiffr needs to run code at the start and end of unit tests (it's most important to run code at the start in order to reset the cases).

**Comment by hadley** [comment]
Yeah, all testthat's regression tests require you to manually manage the files. I think it'll remain that way for a while.
