### ISSUE TITLE
FR: Reporter that prints the location of all expectations

### ISSUE THREAD

**Issue by krlmlr** [hadley/testthat#551]
Useful to locate test code that triggers a particular line of C++ or R code.

**Comment by hadley** [comment]
You're thinking of this when you get a segfault in the tests and want to quickly narrow down the code that causes it?

**Comment by krlmlr** [comment]
This, and also if I just set a breakpoint in C++ code and want to find the code that triggers it.

**Comment by krlmlr** [comment]
Awesome, thanks!

**Comment by krlmlr** [comment]
@hadley: Just used it for the first time, works as advertised. I've noticed two things:

- The reporter prints absolute paths on my system, is this intended?
- It would be helpful if it also printed the locations of each `test_that()` call (entry and exit)

**Comment by hadley** [comment]
Probably not - I'd be happy to review a PR.
