### ISSUE TITLE
Give expect_equivalent a ... arg for tolerance/scale comparison

### ISSUE THREAD

**Issue by richierocks** [hadley/testthat#552]
If I want to control the numeric tolerance while comparing a named numeric vector and an unnamed numeric vector, it isn't clear how to do this right now. `expect_equivalent` is the obvious choice since it is designed for comparing without attributes, but that currently doesn't accept `tolerance` or `scale` args to pass on to `compare`/`all.equal`.

To me, it makes sense let `expect_equivalent` have a `...` argument, just like `expect_equal` to allow this sort of check. 

An example:

```{r}
x <- setNames(1:5 * 1e-10, letters[1:5])
y <- jitter(x, amount = 1e-10)
# this passes
expect_equivalent(x, y)

# I can't provide stronger tol check right now
expect_equivalent(x, y, tolerance = 1e-13)
```

**Comment by hadley** [comment]
Sounds reasonable. Want to do a PR?

**Comment by hadley** [comment]
I have a few hours on a plane, so I'll do it :)
