### ISSUE TITLE
Tolerance 2x too large?

### ISSUE THREAD

**Issue by cdriveraus** [hadley/testthat#560]
Perhaps I have misread something... but running:
expect_equal(2,3,tolerance=.49)    
expect_equal(2,3,tolerance=.51)

the first fails and the latter passes, although the difference is correctly reported (when failing) as -1. If this is not a bug, perhaps the tolerance help could be changed?

**Comment by hadley** [comment]
It's a relative tolerance.  See `all.equal()` for details
