### ISSUE TITLE
[documenation][feature][expectation] Documentation: How to perform parameterized testing

### ISSUE THREAD

**Issue by cogmind** [hadley/testthat#563]
In a previous edit of this issue, I suggested that there was an error when parsing sys.calls from `mapply`. However, this was incorrect and I have now realized how to do **parametric** or **parameterized** testing. Perhaps it would be a welcomed addition to the documentation:

```R
context('Primitive Types')

type <- list(
	"logical", "integer", "double",
	"complex", "character",
	"raw",
	"list",
	"NULL",
	"closure",
	"environment"
) # End list

exemplar <- list(
	FALSE, 3L, 2.0,
	2i, character(),
	raw(2),
	list(1,2,3),
	NULL,
	function(x) { function(x) {return(x+x)}},
	environment()
) # End list

# For each examplar, expect a certain type:
test_that('Primitives: Success', {mapply(expect_type, exemplar, type)})

failures <- list(
	3L, 2.0, 2i,
	character(), raw(2),
	list(1,2,3),
	NULL,
	function(x) { function(x) {return(x+x)}},
	environment(), FALSE
)#  End list

# Break all tests (by shifting the array exemplars array to failures)
test_that('Primitives: Failures', {mapply(expect_type, failures, type)})

```

> Primitive Types: ..........123456789a
> 
> Failed -------------------------------------------------------------------------
> 1. Failure: Primitives: Failures (@testTYPEprimitives.R#42) --------------------
> dots[[1L]][[1L]] has type `integer`, not `logical`.
> 
> 
> 2. Failure: Primitives: Failures (@testTYPEprimitives.R#42) --------------------
> dots[[1L]][[2L]] has type `double`, not `integer`.
> 
> 
> 3. Failure: Primitives: Failures (@testTYPEprimitives.R#42) --------------------
> dots[[1L]][[3L]] has type `complex`, not `double`.
> 
> 
> 4. Failure: Primitives: Failures (@testTYPEprimitives.R#42) --------------------
> dots[[1L]][[4L]] has type `character`, not `complex`.
> 
> 
> 5. Failure: Primitives: Failures (@testTYPEprimitives.R#42) --------------------
> dots[[1L]][[5L]] has type `raw`, not `character`.
> 
> 
> 6. Failure: Primitives: Failures (@testTYPEprimitives.R#42) --------------------
> dots[[1L]][[6L]] has type `list`, not `raw`.
> 
> 
> 7. Failure: Primitives: Failures (@testTYPEprimitives.R#42) --------------------
> dots[[1L]][[7L]] has type `NULL`, not `list`.
> 
> 
> 8. Failure: Primitives: Failures (@testTYPEprimitives.R#42) --------------------
> dots[[1L]][[8L]] has type `closure`, not `NULL`.
> 
> 
> 9. Failure: Primitives: Failures (@testTYPEprimitives.R#42) --------------------
> dots[[1L]][[9L]] has type `environment`, not `closure`.
> 
> 
> 10. Failure: Primitives: Failures (@testTYPEprimitives.R#42) -------------------
> dots[[1L]][[10L]] has type `logical`, not `environment`.
> 
> 
> DONE ===========================================================================
> >

**Comment by hadley** [comment]
This will be easier once testthat uses quasiquotation which should happen in the next release.
