### ISSUE TITLE
skip_if_localized()

### ISSUE THREAD

**Issue by krlmlr** [hadley/testthat#565]
to be able to skip tests that check the wording of an error message and fail in a non-English locale.

**Comment by hadley** [comment]
Or we could add a language parameter to `expect_error()`? That's more likely to affect existing code, but it might be easy to discover.

**Comment by hadley** [comment]
Hmmm, how do we know if you're localised?

**Comment by gaborcsardi** [comment]
Maybe `Sys.getenv("LANGUAGE")` based on `?"environment variables"`?

**Comment by gaborcsardi** [comment]
This should be better I guess: https://github.com/wch/r-source/blob/0af92cb369681f3ef666451a6eeb895988c04113/tests/reg-tests-1d.R#L13-L29

**Comment by hadley** [comment]
Something like

```R
is_english <- function() {
  lang <- Sys.getenv("LANGUAGE")
  if (identical(lang, "en")) {
    return(TRUE)
  }
  
  if(.Platform$OS.type == "windows") {
    lc <- sub("\\..*", "", sub("_.*", "", Sys.getlocale("LC_CTYPE")))
    lc == "English" || lc == "C"
  } else {
    lc <- sub("\\..*", "", Sys.getlocale("LC_MESSAGES"))
    lc == "C" || substr(lc, 1, 2) == "en"
  }
}
```

**Comment by hadley** [comment]
We need a different name because of localized vs localised. Maybe `skip_if_not_en()`?

**Comment by hadley** [comment]
This feels awkward - I'd rather add a lang parameter to `expect_error()`

**Comment by hadley** [comment]
Unfortunately it looks like that gettext caches translations between calls making it difficult to switch languages back and forth in a single session.  I'll go back to `skip_if_translated()`
