### ISSUE TITLE
skip_on_oldrel()

### ISSUE THREAD

**Issue by lionel-** [hadley/testthat#571]
To skip tests on old R releases:

```r
skip_on_oldrel <- function(version, msg = NULL) {
  if (utils::packageVersion("base") < version) {
    msg <- msg %||% paste("R version too old:", version)
    skip(msg)
  }
}
```

**Comment by hadley** [comment]
I think we should generalise this to:

```R
skip_on_r_version("= 3.1")
skip_on_r_version(">= 3.1")
```

etc

**Comment by gaborcsardi** [comment]
```r
skip_on_r_version("==", "3.1")
skip_on_r_version("<=", "3.1")
```
etc. is easier to implement (no parsing needed) , and just as easy to write, and it is also easier to write programmatically. I think.

**Comment by lionel-** [comment]
Good idea. Going further, making it a functional would be even easier to implement, more flexible (it'd accept arbitrary comparison functions which could handle edge cases more easily) and more idiomatic for R:

```r
skip_on_r_version(`==`, "3.1")
skip_on_r_version(my_predicate, "3.1")
```

**Comment by hadley** [comment]
@lionel- only a limited number of operators have been implemented for working with version objects, so I'd rather keep it simple for now

**Comment by kevinushey** [comment]
What about just punting to a more general `skip_if`, e.g.

    skip_if(getRversion() > "3.1.0")

The `skip_on_r_version()` signature seems easy to get wrong as a user.

**Comment by hadley** [comment]
The advantage of a more specific method is a better message, but `skip_if()` seems worthwhile even if we do have `skip_on_r_version()`.

**Comment by hadley** [comment]
Comparing these options:

```R
skip_if(getRversion() == "3.1.0")
skip_on_r_version(`==`, "3.1.0")
```

I don't think the more specific skip is any more appealing.

**Comment by gaborcsardi** [comment]
Maybe the message would be nicer for the second one?
