### ISSUE TITLE
Hooks to run code at the start and end of testing session

### ISSUE THREAD

**Issue by lionel-** [hadley/testthat#572]
Would be useful for vdiffr and other testthat extensions

**Comment by hadley** [comment]
Are you imagining actual hooks? (i.e `setHook()`/`getHook()`)

**Comment by lionel-** [comment]
I thought these hooks only worked with package events? Hmm it doesn't look like you can use these functions for arbitrary events. Do we need a more general mechanism in rlang?

**Comment by hadley** [comment]
@lionel- hooks are just a naming convention. We'd provide some wrapper around `getHook("testthat::setup")`

**Comment by hadley** [comment]
Alternatively, these extensions could just automatically insert a (e.g.) `setup-vdiffr.R` file, once #589 is implemented.

**Comment by lionel-** [comment]
Sounds good. vdiffr also needs code that runs before the tests start.

**Comment by hadley** [comment]
I'm going to close this, assuming that testthat helpers will just add their own setup/teardown files to the directory.
