### ISSUE TITLE
Teamcity reporter issue

### ISSUE THREAD

**Issue by hesamaseh** [hadley/testthat#574]
Hi im trying to use the teamcity reporter but it doesn't work. Do i need to any thing special to make the teamcity reporter working ? Thanks

**This is the error that i get**

> test_check("LGD", reporter = "TeamcityReporter")
Loading required package: LGD
Error: Can not find test reporter TeamcityReporter
Execution halted

checking PDF version of manual ... OK
DONE

**This is the content of my testthat.R**

library(testthat)

test_check("LGD", reporter = "TeamcityReporter")

**Testthat version** 

> packageVersion("testthat")
[1] ‘1.0.2’

**Comment by hadley** [comment]
The syntax is `test_check("LGD", reporter = "teamcity")`

**Comment by hesamaseh** [comment]
Thanks for the quick response, but it seems that the teamcity reporter doesnt work properly. It shows completely different results and doesn't even show the failed results. Also where can i find the list of reporters that i can use, i cant seem to find it. Thanks.

**Regular results not using teamcity reporter** 

1. Failure: Group CC-AB-1-Lifetime-Baseline  (ND) has 19 projection periods - should be 20 (@test_lgd.R#154)
  `n.proj.periods` not identical to `actual.proj.periods`.
  1/1 mismatches
  [1] 20 - 19 == 1


  testthat results ================================================================
  OK: 3569 SKIPPED: 0 FAILED: 1
  1. Failure: Group CC-AB-1-Lifetime-Baseline  (ND) has 19 projection periods - should be 20 (@test_lgd.R#154)

  Error: testthat unit tests failed
  Execution halted
* checking PDF version of manual ... OK
* DONE


**Teamcity reporter results** 


 ERROR
Running the tests in ‘tests/testthat.R’ failed.
Last 13 lines of output:

  ##teamcity[testSuiteStarted name='Group MOR-QC-4-Pessimistic  (D) appears 1 times in output - should be 1']
  ##teamcity[testStarted name='expectation 1']
  ##teamcity[testFinished name='expectation 1']
  ##teamcity[testSuiteFinished name='Group MOR-QC-4-Pessimistic  (D) appears 1 times in output - should be 1']

  ##teamcity[testSuiteStarted name='Group MOR-QC-4-Pessimistic (D) has 1 projection periods - should be 1']
  ##teamcity[testStarted name='expectation 1']
  ##teamcity[testFinished name='expectation 1']
  ##teamcity[testSuiteFinished name='Group MOR-QC-4-Pessimistic (D) has 1 projection periods - should be 1']

  Error: Test failures
  Execution halted

Great project keep it up :) :+1:

**Comment by hadley** [comment]
Team city was a contributed reporter, so I don't know much about it. If there's a problem I'd recommend creating a minimal reproducible example (probably easiest to host a tiny package elsewhere on github), and filing a new issue.
