### ISSUE TITLE
expect_equal, no tol=? expect-failure testing

### ISSUE THREAD

**Issue by dougpagani** [hadley/testthat#577]
I encountered a bug when something should've failed which did not in my own code.
I was trying to use `expect_equal` with a `tol=` arg, and I changed something which should've flunked an expectation.

I looked into the test-set for this package, and it seems there is no **expect-failure** for two objects failing the tolerance criterion. Testing this myself, it seems sometimes it works, but there are edge cases for which it behaves as it clearly should not.

Examples:

`expect_equal(3000,3001)` #> Fails, as it should.  

`expect_equal(3000, 3001, tol = 2)` #> passes, as it should.  

`expect_equal(3000, 4000, tol = 0.1)` #> Fails, as it should.  

`expect_equal(3000, 3001, tol = 0.1)` #> **PASSES, for which it should NOT**.
--> (Falls outside the tolerance window)

`expect_equal(3000, 3001, tol = 0.1, scale = 1)` #> Fails, back to intended behavior.  

`expect_equal(3000, 3001, tol = 0.1, scale = NULL)` #> PASSES, for which *I believe* it should not.  

Unless there are tests for the equality set elsewhere, it looks like this bug would've fallen-through development since there are no tests in its associated test-file which test for **failing tolerance intervals:**

https://github.com/hadley/testthat/blob/master/tests/testthat/test-expect-equality.R

**Comment by hadley** [comment]
`expect_equal()` depends on `all.equal()` for tolerance, so the problem likely lies there.
