### ISSUE TITLE
Correct way to loading JARs to the classpath  within testthat?

### ISSUE THREAD

**Issue by zachcp** [hadley/testthat#582]
Hi Team Testthat,

I have been writing a package that [uses rJava and some additional JAR files](https://github.com/zachcp/archaeopteryx-js). The package loads just fine and code runs well but in testthat I get errors indicating the classes are not being recognized:

```
1. Error: PhyloJ objects can be created correctly (@test-phyloJ.R#16) ----------
RcallMethod: cannot determine object class
1: create_phyloJ(phylo = tree, seqs = dna1) at /Users/zach/Projects/Software/archaeopteryx/tests/testthat/test-phyloJ.R:16
2: parse_newick(write.tree(as(phylo, "phylo"))) at /Users/zach/Projects/Software/archaeopteryx/R/create_phyloJ.R:43
3: .jcall("org/forester/phylogeny/Phylogeny", "Lorg/forester/phylogeny/Phylogeny;", 
       "createInstanceFromNhxString", newick) at /Users/zach/Projects/Software/archaeopteryx/R/parse_newick.R:9
```

Furthermore, if I try to force the loading to JARs in a testthat file, i run into an Issue:
```
# this still fails
.jinit()
.jaddClassPath(Sys.glob(paste0(system.file("JARs/", package = "archaeopteryx"),"*")))
```

Is there a correct way to ensure the classpath is loaded correctly? Does`testthat` not respect the `.onload()` function? Any pointers would be highly appreciated.

thanks,
zach cp

**Comment by hadley** [comment]
You should be able to set this in `.onLoad()`.
