### ISSUE TITLE
bug in reporter-check.R

### ISSUE THREAD

**Issue by stla** [hadley/testthat#584]
Hello, 

 I have a test which fails and there's a bug coming from [reporter-check.R](https://github.com/hadley/testthat/blob/bc38b8774b879cea8d8b470f4a69328e57965e95/R/reporter-check.R).

When I run `test_check` :
```
testthat results =======================================================
OK: 124 SKIPPED: 0 FAILED: 1
Error in vapply(show, failure_header, character(1)) : 
  values must be length 1,
 but FUN(X[[1]]) result is length 3
```

When I click on "Test package" in RStudio:

```
Failed -------------------------------------------------------------------------
Error in rep("-", linewidth) : invalid 'times' argument
Calls: <Anonymous> ... <Anonymous> -> vapply -> FUN -> summary_fun -> paste
```

**Comment by stla** [comment]
I see, that's because I forgot to give a name to the tests block:
```
test_that({
  mytests...
})
```

**Comment by hadley** [comment]
Seems to have been fixed - I now see a useful error message.
