### ISSUE TITLE
Error when summarizing the test cases

### ISSUE THREAD

**Issue by gaborcsardi** [hadley/testthat#587]
I get this after running a rather big test suite, the dev version of `igraph`:

```
  testthat results ============================================================
  OK: 3722 SKIPPED: 1 FAILED: 0
  Error in rbind(deparse.level, ...) : 
    numbers of columns of arguments do not match
  Calls: test_check ... as.data.frame.testthat_results -> do.call -> <Anonymous> -> rbind
```

This is on CRAN's win-builder, so all CRAN packages.

Has anyone seen this before? I am just trying my luck here.... If not, I'll try to create a smaller reprex. Thanks!

**Comment by hadley** [comment]
I haven't seen this before. Did you manage to figure it out?

**Comment by gaborcsardi** [comment]
I think this was fixed already. It happens if a block (or a context?) had no tests at all.
