### ISSUE TITLE
Should I use Escape characters? Is it so important?

### ISSUE THREAD

**Issue by agricolamz** [hadley/testthat#588]
I found out really strange behavior of the `warning()` and `expect_warning()`.
Firstly my problem was here
```
expect_warning(warning("oh-oh (nice try)"), "oh-oh (nice try)")
```
That gives me meaningless warning, that probably could be changed.
```
`warnings` does not match "oh-oh (nice try)".
Actual value: "oh-oh (nice try)"
```
Ok. I find out that I should use escape characters, so this works:
```
expect_warning(warning("oh-oh (nice try)"), "oh-oh \\(nice try\\)")
```
I can't find anything about it in documentation. So may be it is could be mentioned somewhere? And I'm still not sure, that it is nice.
Then I found some more strangeness:
```
expect_warning(warning("oh-oh (nice try)"), "oh-oh") # pass without mistakes
expect_warning(warning("oh-oh \\(nice try\\)"), "oh-oh") # pass without mistakes
```
May be I missed something important in Regex syntax details in R?

**Comment by gaborcsardi** [comment]
> May be I missed something important in Regex syntax details in R?

Maybe:

```r
grepl("oh-oh", "oh-oh (nice try)")
#> [1] TRUE
grepl("oh-oh", "oh-oh \\(nice try\\)")
#> [1] TRUE
```

If you don't want to deal with regular expressions, then use `fixed = TRUE`:

```r
expect_warning(warning("oh-oh (nice try)"), "oh-oh (nice try)", fixed = TRUE)
```

**Comment by agricolamz** [comment]
Thanks!
