### ISSUE TITLE
Setup and teardown files

### ISSUE THREAD

**Issue by hadley** [hadley/testthat#589]
These functions would be run at the end of the all the tests.  Would not be sourced by `load_all()`

**Comment by gaborcsardi** [comment]
Might or might not be useful: https://github.com/hadley/testthat/pull/158

**Comment by hadley** [comment]
Oh yeah, just like that 😬

**Comment by kimyen** [comment]
I am looking for this. My use case: I am working on [PythonEmbedInR](https://github.com/Sage-Bionetworks/PythonEmbedInR), a fork of PythonInR. 
Users of this package may or may not change their option to use pandas (in python). However, I need to test that the functions work when users choose to use pandas. 
Before running my tests, I want to install pandas. After the tests ran, I want to remove pandas. I want to install and remove pandas only once. 
My current work around is installing pandas using helper.R and removing pandas in testthat.R, after test_check(). It would be much nicer if I can put all the code that remove pandas to a teardown-prefix file.

**Comment by hadley** [comment]
Maybe we should also add `setup-` prefix which would be run only by testthat, not by `devtools::load_all()`.

**Comment by gaborcsardi** [comment]
@hadley Yeah, probably. I am really not sure what you want for `load_all()`.
