### ISSUE TITLE
Add support to mark tests as known failures

### ISSUE THREAD

**Issue by fritzo** [hadley/testthat#592]
A common TDD workflow is to add a "known failing" test as soon as a bug is reported, and then remove the "known failing" annotation once the bug is fixed. To support this workflow, `testthat` could say add a parameter `known.failure` or `warn.on.failure` as in
```
test_that("Bug #1234", known.failure = "TODO(fritzo)", {
   # Run the example provided in bug report.
   ...
})
```
This feature is useful when you have thousands of tests some small percent of which are know to fail, and a single cleanup commit may fix 5 tests but break 2 others.

Note that this FR is distinct from `expect_failure` which annotates a single expectation, rather than a test with multiple expectations.

**Comment by fritzo** [comment]
My current workaround is to define a global variable `RUN_FAILING_TESTS = FALSE` and annotate
```
if(RUN_FAILING_TESTS)
test_that("Bug #1234", {
   # Run the example provided in bug report.
   ...
})
```

**Comment by hadley** [comment]
You can use `skip()` for this purpose.
