### ISSUE TITLE
expect_equal numeric tolerances don't work for tibbles

### ISSUE THREAD

**Issue by swt30** [hadley/testthat#593]
```R
library(tibble)
d1 = data.frame(col = c(1, 2))
d2 = data.frame(col = c(1, 2.000000000001))
t1 = as_data_frame(d1)
t2 = as_data_frame(d2)

library(testthat)
expect_equal(d1, d2)
expect_equal(t1, t2)
```
The first assertion passes, but the second fails with 
```
Error: `t1` not equal to `t2`.
Rows in x but not y: 2. Rows in y but not x: 2. 
```
This is using the default tolerance of `sqrt(.Machine$double.eps)`, but it will fail even if you set `tolerance = 0.1`.

I'm using R 3.3.1, testthat 1.0.2, tibble 1.3.0.

**Comment by ElsLommelen** [comment]
This issue is related to [this issue in tibble](https://github.com/tidyverse/tibble/issues/287) and should be solved there.
