### ISSUE TITLE
running code in expect_warning gives different error than observed in consule

### ISSUE THREAD

**Issue by epurdom** [hadley/testthat#599]
I am using `testthat` for my package, and I have a situation where a function I wrote should produce a warning. I set up a test using `expect_warning` for this situation and it creates this warning when I enter it on the command line. However, when I run the same command in `expect_warning` it doesn't get this warning and apparently hits an error that I don't get on the command line. (R3.4, testthat 1.0.2).

Unfortunately, I don't have a minimal example and wouldn't even know where to begin to make one, because I'm totally baffled. I was hoping someone would have some suggestion for how I could try to track this down further. 

Here is my command and the warning my function gives when running at the command line:

<pre>
> plotHeatmap(smSimCE, whichClusters="all", alignSampleData=TRUE, overRideClusterLimit=TRUE)
Warning message:
In .local(data, ...) :
  More than 10 annotations/clusterings can result in incomprehensible errors in aheamap. You have >10 but have chosen to override the internal stop by setting overRideClusterLimit=TRUE.
</pre>

When I run it with `expect_warning`, even without giving it text to try to match, I get the following:

<pre>
> expect_warning(plotHeatmap(smSimCE, whichClusters="all", alignSampleData=TRUE, overRideClusterLimit=TRUE))
Error in .local(clusters, whichClusters, ...) : 
  clusters should not have 'NA' values; non-clustered samples should get a '-1' or '-2' value depending on why they are not clustered.
</pre>

This is a possible error catch in a different function called by the plotHeatmap command, but I don't get it at the command line. A priori I don't think this call should be hitting the error, but of course, given that I can't recreate the error except inside the `expect_warning` construct it is difficult to be 100% certain (my `plotHeatmap` function is quite extensive, and with this set of options, it is calling another intricate function which is the one that has this error catch). 

Similarly, if I run this command in `testthat` command it hits an error:

<pre>
> test_that("`plotHeatmap` test", {    plotHeatmap(smSimCE,whichClusters="all",alignSampleData=TRUE,overRideClusterLimit=TRUE)
+ })
Error: Test failed: '`plotHeatmap` test'
* clusters should not have 'NA' values; non-clustered samples should get a '-1' or '-2' value depending on why they are not clustered.
1: plotHeatmap(smSimCE, whichClusters = "all", alignSampleData = TRUE, overRideClusterLimit = TRUE) at :1
2: plotHeatmap(smSimCE, whichClusters = "all", alignSampleData = TRUE, overRideClusterLimit = TRUE)
3: .local(data, ...)
4: do.call("plotHeatmap", c(list(data = heatData, clusterSamplesData = clusterSamplesData, clusterFeaturesData = heatData, 
       sampleData = sampleData, whSampleDataCont = whSampleDataCont, clusterSamples = clusterSamples, labRow = labRow, 
       clusterLegend = clLegend, clusterFeatures = clusterFeatures, colorScale = colorScale), userList))
5: plotHeatmap(data = structure(c(3.70043971814109, 3.58496250072116, 0, 8.11374216604919, 0, 0, 6.7279204545632, 
   2.32192809488736, 0, 0, 2.32192809488736, 0, 1, 2.32192809488736, 0, 1, 3, 0, 0, 1, 14.6213078524619, 0, 5.93073733756289, 
   0,
</pre>

And of course if I run the test I was trying to run, which matches the warning error to the expected text, it similarly fails:

<pre>
> expect_warning( plotHeatmap(smSimCE, whichClusters="all", alignSampleData=TRUE, overRideClusterLimit=TRUE)
+ , "More than 10 annotations/clusterings")
Error in .local(clusters, whichClusters, ...) : 
  clusters should not have 'NA' values; non-clustered samples should get a '-1' or '-2' value depending on why they are not clustered.
</pre>

**Comment by hadley** [comment]
It might be slightly easier to debug if you run it with `capture_warnings()`.

Unfortunately debugging this sort of problem is generally painful. You just need to systematically test your assumptions until you figure out the one that's wrong.

If you're totally stuck, you might try asking on http://community.rstudio.com/, but you'll need some sort of reproducible example (minimal or otherwise).

**Comment by ramiromagno** [comment]
hi @hadley:

Using testthat 2.0.0.

Not sure if my problem is related to OP's problem. Here's the code that illustrates my issue:

Definition of function `drop_links`:

 ```R
drop_links <- function(lst) {

  if(!identical(typeof(lst), "list"))
    stop("lst must be of type list.")

  # If list is empty, do nothing and return as is.
  if(length(lst) < 1L) {
    warning("Input list is empty. Nothing to do. Returning the input list as is.")
    return(lst)
  }
}
```
And here's the test that gives me trouble:

```R
test_that("Test drop_links", {
  empty_lst <- list()
  warn_msg <- "Input list is empty. Nothing to do. Returning the input list as is."
  expect_warning(drop_links(empty_lst), warn_msg)
})
```

The unexpected output from `devtools::test()`:

```
???: error: Test drop_links
object 'lst' not found
1: test_code(desc, code, env = parent.frame())
2: tryCatch(withCallingHandlers({
       eval(code, test_env)
       if (!handled && !is.null(test)) {
           skip_empty()
       }
   }, expectation = handle_expectation, skip = handle_skip, warning = handle_warning, 
       message = handle_message, error = handle_error), error = handle_fatal, 
       skip = function(e) {
       })
3: tryCatchList(expr, classes, parentenv, handlers)
4: tryCatchOne(tryCatchList(expr, names[-nh], parentenv, handlers[-nh]), names[nh], 
       parentenv, handlers[[nh]])
5: doTryCatch(return(expr), name, parentenv, handler)
6: tryCatchList(expr, names[-nh], parentenv, handlers[-nh])
7: tryCatchOne(expr, names, parentenv, handlers[[1L]])
8: value[[3L]](cond)
```
