### ISSUE TITLE
missing documentation about integration with jenkins (junit reporter)

### ISSUE THREAD

**Issue by 3psil0n** [hadley/testthat#601]
Hey everyone,

In my opinion, the README file should list some more information about "advanced" options of testthat. I'm aware of the fact that this is not a software issue. However, it acts as a deterrent if there is no documentation for standard JUnit XML output (JUnitReporter). 
Many developers need the XML output for CI with e.g. Jenkins. 

Thanks,

3psil0n

**Comment by jdshkolnik** [comment]
I'm glad you opened this. I can't seem to get it to work. It is as simple as adding an options line similar to below? Which folder would it appear in?

```
library(testthat)
options(testthat.junit.output_file = "junit_test_results.xml")
test_check("something")
```

**Comment by 3psil0n** [comment]
@jdshkolnik  According to the documentation and the news messages, I think your code should work. But it doesn't work for me.

**Comment by jdshkolnik** [comment]
@3psil0n That's because they haven't released everything you see in the news. See #604

**Comment by hadley** [comment]
I don't use jenkins, so I'm reliant on pull requests. Would you like to contribute one?
