### ISSUE TITLE
Test hanging in R CMD check but not when run interactively

### ISSUE THREAD

**Issue by p-smirnov** [hadley/testthat#602]
I have recently started using testthat to unit test our ``PharmacoGx`` Bioconductor package, and I have run into an issue with the expect_equal_to_reference test. This following code in testing our package runs interactively (using both devtools::check() and check_package()), but when called by R CMD check hangs indefinitely (R stops using any CPU resources for upwards of half hour, must be interrupted to continue check with errors due to interruption):
```
library(PharmacoGx)
require(parallel)
context("Checking intersectPSet.")

test_that("Intersection result did not change since last time", {
	data(GDSCsmall)
	data(CCLEsmall)
	expect_equal_to_reference(intersectPSet(list('GDSC'=GDSCsmall, 'CCLE'=CCLEsmall), intersectOn = c("drugs", "cell.lines","concentrations")), "intersectedSmallData.rds")
})
```
I have narrowed down the issue to specifically the setting of the parameter: `` intersectOn = c("drugs", "cell.lines","concentrations")``, with the setting `` intersectOn = c("drugs", "cell.lines")`` working properly in both cases.

The main difference is that when concentrations is included in the list, the code calls a function (``PharmacoGx:::.calculateSensitivitiesStar``) which relies on ``makeCluster``  and ``parSapply`` from the parallel package. ``makeCluster`` is called with 1 as the parameter, and this same code (``intersectPSet(list('GDSC'=GDSCsmall, 'CCLE'=CCLEsmall), intersectOn = c("drugs", "cell.lines","concentrations"))`` runs fine as part of the documentation examples when run by R CMD check. 

Given that I cannot reproduce this issue interactively, I am having trouble probing the issue and creating a more minimal working example. Maybe someone with more knowledge of the exact environment in which R CMD check runs the tests can help me reproduce the issue in an R session?

**Comment by gaborcsardi** [comment]
This might be something else, but just to rule it out, can you please quickly try the workaround mentioned here: https://github.com/hadley/devtools/issues/1526#issuecomment-309093701

Thanks.

**Comment by p-smirnov** [comment]
@gaborcsardi: Thank you, that solved the issue! For some reason my search of the issues didn't turn up the previous one.

**Comment by dbaston** [comment]
For me, the issue was resolved by adding `library(Rcpp)` to the top of `testthat.R`.
