### ISSUE TITLE
Unset R_TESTS

### ISSUE THREAD

**Issue by gaborcsardi** [hadley/testthat#603]
It only causes trouble, it is not actually doing anything useful.

**Comment by hadley** [comment]
Always, or just in `test_check()`?

**Comment by gaborcsardi** [comment]
why not always? to have consistent behavior?.

**Comment by hadley** [comment]
Ok, sure thing.

**Comment by gaborcsardi** [comment]
Yes, it fixes #86.

**Comment by wlandau-lilly** [comment]
Perfect!

**Comment by hughjonesd** [comment]
I used to use the presence of R_TESTS to skip certain tests which don't play well with R CMD check. Is there an alternative? I'm aware of skip_on_cran and friends.

**Comment by gaborcsardi** [comment]
@hughjonesd you can set an environment variable in `tests/testthat.R`. This only runs for `R CMD check`.

**Comment by hughjonesd** [comment]
Got it. Thank you.
