### ISSUE TITLE
Estimate as to next release (1.0.3?)

### ISSUE THREAD

**Issue by jdshkolnik** [hadley/testthat#604]
Hi,

[v1.0.2](https://github.com/hadley/testthat/releases/tag/v1.0.2) was released over a year ago and [v1.0.2.9000](https://github.com/hadley/testthat/blob/c7e8330867645c174f9a286d00eb0036cea78b0c/NEWS.md#testthat-1029000) is already looking pretty hefty. Any idea as to when the next version will be released?

**Comment by jdshkolnik** [comment]
Is this project abandoned?

**Comment by hadley** [comment]
Hopefully in the next month or so
