### ISSUE TITLE
How can I test that a function prints NULL?

### ISSUE THREAD

**Issue by bradleyjeck** [hadley/testthat#608]
In the following, the function f() returns NULL and prints this to the R console. Yet expect_output() fails and expect_silent() does not. 

```
> f <- function() return()
> f()
## NULL
> expect_output( f() ) 
## Error: f() produced no output
> expect_silent( f() )
## 
```

Any advice appreciated.

**Comment by gaborcsardi** [comment]
Your `f` does not really *print* `NULL`, it just returns it. If you want to test this behavior, use

```r
expect_null(f())
```

If you really want to test the printing with `expect_output`, then you need to explicitly print it:

```r
expect_output(print(f()), "NULL")
```

**Comment by bradleyjeck** [comment]
Ok.   In my case, I want the printing of `NULL` on the on the console to be a test failure even though `NULL` is the correct return value.  Put another way, I want to confirm my functions return invisibly. How can I test for that?

**Comment by gaborcsardi** [comment]
OK. Your `f` does not return the `NULL` invisibly, imo. For that you need to return `invisible()`. Anyway, this is how to test this:

```r
f <- function() return()
f2 <- function() return(invisible())
expect_false(withVisible(f())$visible)
expect_false(withVisible(f2())$visible)
```

**Comment by bradleyjeck** [comment]
Great, thanks!
