### ISSUE TITLE
change expect_silent to include object output

### ISSUE THREAD

**Issue by r2evans** [hadley/testthat#615]
(This is softly mentioned #614, and related to it since I'm trying to replace `info` functionality.)

I want to test for silence (or warning or error) from a function and still test its output. If a function is "expensive", I'd much rather not run it multiple times. However, the current `expect_silent` and family explicitly discard the object upon execution.

Right now I can do

```r
expect_silent2 <- function(obj) { expect_silent(o <- obj) ; o ; }
```

but this does not work using the NSE hack for replacing `info`. That is:

```r
expect_silent(myfunc(FALSE))
expect_silent(myfunc(TRUE))
# Error: myfunc(TRUE) produced warnings.
expect_silent2(myfunc(FALSE))
# [1] FALSE
expect_silent2(myfunc(TRUE))
# Error: o <- obj produced warnings.
```

That last error message isn't very useful, so I try the NSE trick:

```r
expect_silent3 <- function(obj) { eval(bquote(expect_silent(.(o <- obj)))) ; o ; }
expect_silent3(myfunc(TRUE))
# Warning in myfunc(TRUE) : quux
# [1] TRUE

expect_silent4 <- function(obj) { eval(bquote(expect_silent(o <- .(obj)))) ; o ; }
expect_silent4(myfunc(TRUE))
# Warning in myfunc(TRUE) : quux
# [1] TRUE

expect_silent5 <- function(obj) eval(bquote(expect_silent2(.(obj))))
expect_silent5(myfunc(TRUE))
# Warning in myfunc(TRUE) : quux
# [1] TRUE
```

but none of them triggers the `Error: myfunc(TRUE) produced warnings` I would expect.

**Comment by hadley** [comment]
Just do the assignment inside the expectation:

```R
expect_silent(x <- foo())
expect_equal(x, 10)
```

But you already know how to do that so I'm not sure what you want.I don't think it make sense for some `expectation()` 

...

Ooooh, all the other expectations return the first object invisibly, so `expect_silent()` etc should be consistent.
