### ISSUE TITLE
Feature request: expect_plot function to check if any plot was send to appropriate device

### ISSUE THREAD

**Issue by twolodzko** [hadley/testthat#617]
Expected output:

```r
expect_plot(hist(rnorm(100), plot = TRUE))
## TRUE
expect_plot(hist(rnorm(100), plot = FALSE))
## FALSE
```

Unfortunately, at this moment I don't have any idea how this could be implemented. Here is one candidate for such function: https://stackoverflow.com/questions/31038709/how-to-write-a-test-for-a-ggplot-plot

**Comment by hadley** [comment]
In general, I'd recommend using [vdiffr](http://github.com/lionel-/vdiffr) for testing plot output.
