### ISSUE TITLE
expect_error() does not find errors that occur after expectations

### ISSUE THREAD

**Issue by maxheld83** [hadley/testthat#618]
I'm using `checkmate` `expect_*()` to run (input) validation for my functions in some package.
If I want to test these validations in turn, using testthat, the usual `expect_error()` does fails, even when the expression *does* in fact error out as it should.

MWE from @mllg:

```
context("nested expect")

foo = function(x) {
  expect_true(x)
  stop("myerror")
}

test_that("nested expect", {
  expect_error(foo("a"), "myerror")
})
```

Issue was originally raised over at `checkmate` in https://github.com/mllg/checkmate/issues/82.
@mllg suspected it might be a testthat issue.

**Comment by hadley** [comment]
So the basic problem is that an error should exit, but a failed expectation should continue running the rest of the code.

**Comment by hadley** [comment]
Hmmmm, it's actually not clear that the current behaviour is wrong. i.e. these tests pass as expected:

```R
test_that("nested expect", {
  foo <- function(x) {
    expect_true(x)
    stop("myerror")
  }
  expect_error(foo(TRUE), "myerror")

  foo <- function(x) {
    expect_true(x)
    stop("myerror")
  }
  expect_error(foo(FALSE), "FALSE isn't true")
})
```
