### ISSUE TITLE
Spinner displayed in R console sits atop the context

### ISSUE THREAD

**Issue by jennybc** [hadley/testthat#624]
Strange interaction between the spinner and other output. This is `hadley/testthat@c7e8330`.
 
![oops](https://user-images.githubusercontent.com/599454/30767543-35b30dc4-9fb2-11e7-9766-3ecb6f949de0.gif)

**Comment by gaborcsardi** [comment]
Probably coming from `callr`, just call `callr` with `spinner = FALSE`, or even `show = FALSE`.

**Comment by hadley** [comment]
@jennybc are you calling callr in your code?

**Comment by jennybc** [comment]
Yes and the spinner is used there for progress reporting:

https://github.com/tidyverse/reprex/blob/e5cff803119c4c2e4cea535078141e3b0987b976/R/reprex.R#L331-L341

**Comment by jennybc** [comment]
And the addition of `&& !in_tests()` by @jimhester has fixed this problem.
