### ISSUE TITLE
Graphical Userface with Green and Red Dots

### ISSUE THREAD

**Issue by bc** [hadley/testthat#625]
I noticed the desire to create a GUI with dots in the Future Work section of testthat. Has this been achieved?

![image](https://user-images.githubusercontent.com/13772726/30787152-6819248e-a137-11e7-84a4-1974540e7fae.png)
reference: https://journal.r-project.org/archive/2011-1/RJournal_2011-1_Wickham.pdf
-Brian

**Comment by hadley** [comment]
Yes, it has. You'll need a daily version of RStudio to see it.
