### ISSUE TITLE
Setup and teardown functions

### ISSUE THREAD

**Issue by hadley** [hadley/testthat#628]
Would be run before/after each test.

Do we also need per-file setup and teardown?

**Comment by gaborcsardi** [comment]
I think we could start with something that runs before *all* tests (which we almost have with `helper-`, barring `load_all()` behavior), and something that runs after *all* tests. 

I.e. sg. like creating a test db, and then cleaning it up.

Per-file setup can be useful as well, I can see that. Maybe you can already do this, actually, by simply putting the code at the beginning of the file, and using `on.exit()`. AFAIR this works when the tests are running via `test_file()`. But it would be nice to formalize / document this. 

I am not sure if per-block setup would be useful, I think you can just manually include that, and I don't see a situation where setup/teardown is needed for *every* block.

**Comment by hadley** [comment]
See #628 for code run before/after all tests.

For per-file setup & teardown, maybe we could start with simple definitions:

```R
setup <- function(x) invisible(x)

teardown <- function(x) {
  # withr trick to call on.exit in parent enviroment
}
```

That would provide a nice set of conventions which we could extend with more sophisticated implementations if needed the future.

**Comment by gaborcsardi** [comment]
> See #628 for code run before/after all tests.

Hmm, #628 is *this* issue.

**Comment by hadley** [comment]
Sorry, #589

**Comment by hadley** [comment]
I think `setup()` should probably behave like local (so there's some point in using it)

But that leads to code that looks like this:

```R
tmp <- tempfile()
setup(writeLines(tmp, "some test data"))
teardown(unlink(tmp))
```

I'm not sure if that's good idea or not.
