### ISSUE TITLE
Provide global option that controls where reporter outputs

### ISSUE THREAD

**Issue by hadley** [hadley/testthat#629]
Includes #612 and replaces "testthat.junit.output_file"

**Comment by nealrichardson** [comment]
Bringing discussion from https://github.com/hadley/testthat/pull/612#issuecomment-334511579 to here: 

> At some point you're going to need to move away from options and call the reporter directly. I think having multiple levels of options makes things too complicated.

Calling the reporter directly was the approach I tried in https://github.com/hadley/testthat/pull/467. It required adding an argument to the Reporter initialize method, which currently doesn't let you pass in a file/connection for output (https://github.com/hadley/testthat/blob/317fa98fde9c95fabf9acc34a13ab557b47b2636/R/reporter.R#L24).

Would you be open to extending the Reporter init method to accept an output location?

**Comment by hadley** [comment]
Yes! I now understand the problem better, and I agree that the solution you proposed in #467 is right. 

Would you mind finishing it off by adding to every output reporter? Maybe with that we don't even need an option?

**Comment by nealrichardson** [comment]
Gladly. Will try to submit a PR with that in the next few days.
