### ISSUE TITLE
skip_on_cran() gives error on my computer

### ISSUE THREAD

**Issue by Stan125** [hadley/testthat#636]
`skip_on_cran()` works as intended when used in a test which is run with `devtools::test()`. However, when sourcing my test script individually, I always get an error

```{r}
library(testthat)
skip_on_cran()
#> Error: On CRAN
```

I think this is because my environment variable `NOT_CRAN` is not `FALSE`, but rather `""`:

```{r}
Sys.getenv("NOT_CRAN")
#> [1] ""
identical(Sys.getenv("NOT_CRAN"), "true")
#> [1] FALSE
```

This leads to me not being able to run my tests individually to check some output, but rather I have to remove the function call beforehand. It would be cool if I could run it in a normal script as well.

One could replace `identical(Sys.getenv("NOT_CRAN"), "true")` with `!identical(Sys.getenv("NOT_CRAN"), "false")` in the function call, for example:
https://github.com/hadley/testthat/blob/17b8b325f2d8100f0694f5fff2e3bbc5ce6edea5/R/skip.R#L100-L106

**Comment by hadley** [comment]
Unfortunately there's no way to work around this - "NOT_CRAN" is also set to "" on CRAN.
